/* ─────────────────────────────────────────────────────────────────
 *  OG Image Path Helper
 *
 *  Constructs the Vercel Blob URL to a pre-generated OG image for
 *  any page on the site. Used by generateMetadata() across all routes.
 *
 *  Images are generated by `scripts/generate-og-images.mjs` and
 *  stored in Vercel Blob under the /og/ prefix.
 * ────────────────────────────────────────────────────────────────── */

const BLOB_BASE = process.env.NEXT_PUBLIC_BLOB_URL || "";
const OG_PREFIX = "/og";

/**
 * Build the full URL to a pre-generated OG image on Vercel Blob.
 *
 * @example
 *   ogImagePath("home")
 *   // → "https://<store>.public.blob.vercel-storage.com/og/home.png"
 *
 *   ogImagePath("resources", "questions", "biology", "mitosis-deck")
 *   // → "https://<store>.public.blob.vercel-storage.com/og/resources/questions/biology/mitosis-deck.png"
 */
export function ogImagePath(...segments: string[]): string {
  return `${BLOB_BASE}${OG_PREFIX}/${segments.join("/")}.png`;
}

/**
 * Build a fully-qualified OG image URL.
 * (Legacy helper — now ogImagePath already returns a full URL.)
 */
export function ogImageUrl(baseUrl: string, ...segments: string[]): string {
  return ogImagePath(...segments);
}
