"use client";

import { useState } from "react";
import { Download, FileText, FileSpreadsheet, Archive, Loader2 } from "lucide-react";

interface DeckItem {
  prompt?: string;
  front?: string;
  back?: string;
  explanation?: string;
  options?: Array<{ label: string; body: string; isCorrect: boolean }>;
  stableId: string;
  ordinal: number;
}

export interface DeckDownloadPanelProps {
  type: "questions" | "flashcards";
  deckTitle: string;
  deckSlug: string;
  items: DeckItem[];
  /** Pre-generated blob URL for the exam PDF (questions only) */
  pdfExamUrl?: string;
  /** Pre-generated blob URL for the study-guide PDF (questions only) */
  pdfStudyGuideUrl?: string;
  /** Pre-generated blob URL for the flashcard PDF (flashcards only) */
  pdfFlashcardsUrl?: string;
}

const ATTRIBUTION_TEXT = `Attribution Instructions
========================

This resource was created by EnterMedSchool.org — Free Medical Education Resources.

When sharing, remixing, or using this content:
- Credit EnterMedSchool.org as the source
- Link to https://entermedschool.org when possible
- For flashcards: retain the "Source: entermedschool.org" line in each card when importing to Anki or other apps

Thank you for supporting free medical education!
`;

function escapeCsv(value: string): string {
  if (value.includes('"') || value.includes(",") || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export default function DeckDownloadPanel({
  type,
  deckTitle,
  deckSlug,
  items,
  pdfExamUrl,
  pdfStudyGuideUrl,
  pdfFlashcardsUrl,
}: DeckDownloadPanelProps) {
  const [loading, setLoading] = useState<string | null>(null);

  const triggerDownload = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleTsv = async () => {
    if (type !== "flashcards") return;
    setLoading("tsv");
    try {
      const BOM = "\uFEFF";
      const header = `# Flashcard deck: ${deckTitle} — Generated by EnterMedSchool.org\n`;
      const rows = items.map(
        (item) =>
          `${item.front ?? ""}\t${(item.back ?? "")} | Source: entermedschool.org`,
      );
      const content = BOM + header + rows.join("\n");
      const blob = new Blob([content], { type: "text/tab-separated-values;charset=utf-8" });
      triggerDownload(blob, `entermedschool-${deckSlug}-flashcards.tsv`);
    } finally {
      setLoading(null);
    }
  };

  const handleCsv = async () => {
    if (type !== "flashcards") return;
    setLoading("csv");
    try {
      const BOM = "\uFEFF";
      const header = `# Flashcard deck: ${deckTitle} — Generated by EnterMedSchool.org\n`;
      const rows = items.map((item) => {
        const front = escapeCsv(item.front ?? "");
        const back = escapeCsv(`${item.back ?? ""} | Source: entermedschool.org`);
        return `${front},${back}`;
      });
      const content = BOM + header + rows.join("\n");
      const blob = new Blob([content], { type: "text/csv;charset=utf-8" });
      triggerDownload(blob, `entermedschool-${deckSlug}-flashcards.csv`);
    } finally {
      setLoading(null);
    }
  };

  const handleZip = async () => {
    setLoading("zip");
    try {
      const JSZip = (await import("jszip")).default;
      const { saveAs } = await import("file-saver");
      const zip = new JSZip();

      zip.file("HOW-TO-ATTRIBUTE.txt", ATTRIBUTION_TEXT);

      if (type === "questions") {
        const pdfUrl = pdfExamUrl;
        if (pdfUrl) {
          const resp = await fetch(pdfUrl);
          const pdfBlob = await resp.blob();
          zip.file(`entermedschool-${deckSlug}-exam.pdf`, pdfBlob);
        }
      } else {
        const pdfUrl = pdfFlashcardsUrl;
        if (pdfUrl) {
          const resp = await fetch(pdfUrl);
          const pdfBlob = await resp.blob();
          zip.file(`entermedschool-${deckSlug}-flashcards.pdf`, pdfBlob);
        }
        const BOM = "\uFEFF";
        const tsvHeader = `# Flashcard deck: ${deckTitle} — Generated by EnterMedSchool.org\n`;
        const tsvRows = items.map(
          (item) =>
            `${item.front ?? ""}\t${(item.back ?? "")} | Source: entermedschool.org`,
        );
        zip.file(
          `entermedschool-${deckSlug}-flashcards.tsv`,
          BOM + tsvHeader + tsvRows.join("\n"),
        );
      }

      const blob = await zip.generateAsync({ type: "blob" });
      saveAs(blob, `entermedschool-${deckSlug}-package.zip`);
    } finally {
      setLoading(null);
    }
  };

  const DownloadButton = ({
    id,
    icon: Icon,
    label,
    onClick,
    href,
  }: {
    id: string;
    icon: React.ComponentType<{ size?: number; className?: string }>;
    label: string;
    onClick?: () => void;
    href?: string;
  }) => {
    const isActive = loading === id;
    const className =
      "flex items-center gap-2 rounded-xl border-2 border-ink-dark bg-white px-4 py-3 text-sm font-semibold text-ink-dark transition-all hover:bg-pastel-lavender disabled:cursor-not-allowed disabled:opacity-60";

    if (href) {
      return (
        <a
          href={href}
          download
          className={className}
        >
          <Icon size={18} />
          {label}
        </a>
      );
    }

    return (
      <button
        type="button"
        onClick={onClick}
        disabled={!!loading}
        className={className}
      >
        {isActive ? (
          <Loader2 size={18} className="animate-spin" />
        ) : (
          <Icon size={18} />
        )}
        {label}
      </button>
    );
  };

  return (
    <div className="rounded-2xl border border-ink-dark/[0.08] bg-white p-5">
      <h3 className="mb-4 flex items-center gap-2 font-display text-lg font-bold text-ink-dark">
        <Download size={20} />
        Download
      </h3>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {type === "questions" && (
          <>
            <DownloadButton
              id="pdf-exam"
              icon={FileText}
              label="PDF Exam"
              href={pdfExamUrl}
            />
            <DownloadButton
              id="pdf-study"
              icon={FileText}
              label="PDF Study Guide"
              href={pdfStudyGuideUrl}
            />
          </>
        )}
        {type === "flashcards" && (
          <>
            <DownloadButton
              id="tsv"
              icon={FileSpreadsheet}
              label="TSV (Anki)"
              onClick={handleTsv}
            />
            <DownloadButton
              id="csv"
              icon={FileSpreadsheet}
              label="CSV"
              onClick={handleCsv}
            />
            <DownloadButton
              id="pdf"
              icon={FileText}
              label="PDF Flashcards"
              href={pdfFlashcardsUrl}
            />
          </>
        )}
        <DownloadButton
          id="zip"
          icon={Archive}
          label="ZIP Package"
          onClick={handleZip}
        />
      </div>
    </div>
  );
}
