// Auto-generated by scripts/pull-db-content.mjs — do not edit manually
import type { FlashcardCategory, FlashcardDeck } from "@/types/flashcard-data";

export const flashcardCategories: FlashcardCategory[] = [
  {
    "id": 1,
    "slug": "premed-biology",
    "name": "Pre-Med Biology",
    "description": "Biology topics for pre-med exam preparation",
    "icon": "dna",
    "color": "green",
    "sortOrder": 10
  },
  {
    "id": 2,
    "slug": "premed-chemistry",
    "name": "Pre-Med Chemistry",
    "description": "Chemistry topics for pre-med exam preparation",
    "icon": "flask",
    "color": "blue",
    "sortOrder": 20
  },
  {
    "id": 3,
    "slug": "premed-physics",
    "name": "Pre-Med Physics & Math",
    "description": "Physics and mathematics for pre-med exams",
    "icon": "calculator",
    "color": "purple",
    "sortOrder": 30
  },
  {
    "id": 4,
    "slug": "premed-logic",
    "name": "Pre-Med Logic & Problem Solving",
    "description": "Critical thinking and logical reasoning",
    "icon": "brain",
    "color": "orange",
    "sortOrder": 40
  },
  {
    "id": 5,
    "slug": "premed-reading",
    "name": "Pre-Med Reading Comprehension",
    "description": "Text analysis and comprehension skills",
    "icon": "book",
    "color": "teal",
    "sortOrder": 50
  },
  {
    "id": 6,
    "slug": "preclinical",
    "name": "Preclinical Sciences",
    "description": "Years 1-2 foundational medical sciences",
    "icon": "microscope",
    "color": "blue",
    "sortOrder": 100
  },
  {
    "id": 7,
    "slug": "clinical",
    "name": "Clinical Medicine",
    "description": "Years 3-6 clinical rotations and practice",
    "icon": "stethoscope",
    "color": "teal",
    "sortOrder": 110
  },
  {
    "id": 8,
    "slug": "anatomy",
    "name": "Anatomy",
    "description": "Human anatomy and dissection topics",
    "icon": "skeleton",
    "color": "coral",
    "sortOrder": 120
  },
  {
    "id": 9,
    "slug": "physiology",
    "name": "Physiology",
    "description": "Human body systems and functions",
    "icon": "heart",
    "color": "red",
    "sortOrder": 130
  },
  {
    "id": 10,
    "slug": "pharmacology",
    "name": "Pharmacology",
    "description": "Drugs, mechanisms, and therapeutics",
    "icon": "pill",
    "color": "purple",
    "sortOrder": 140
  },
  {
    "id": 11,
    "slug": "pathology",
    "name": "Pathology",
    "description": "Disease mechanisms and pathophysiology",
    "icon": "virus",
    "color": "orange",
    "sortOrder": 150
  },
  {
    "id": 12,
    "slug": "cardiology",
    "name": "Cardiology",
    "description": "Cardiovascular medicine",
    "icon": "heart",
    "color": "red",
    "sortOrder": 200
  },
  {
    "id": 13,
    "slug": "neurology",
    "name": "Neurology",
    "description": "Nervous system and neurological conditions",
    "icon": "brain",
    "color": "purple",
    "sortOrder": 210
  },
  {
    "id": 14,
    "slug": "internal-medicine",
    "name": "Internal Medicine",
    "description": "General internal medicine topics",
    "icon": "clipboard",
    "color": "blue",
    "sortOrder": 220
  },
  {
    "id": 15,
    "slug": "surgery",
    "name": "Surgery",
    "description": "Surgical principles and procedures",
    "icon": "scalpel",
    "color": "gray",
    "sortOrder": 230
  },
  {
    "id": 16,
    "slug": "pediatrics",
    "name": "Pediatrics",
    "description": "Child health and development",
    "icon": "baby",
    "color": "pink",
    "sortOrder": 240
  },
  {
    "id": 17,
    "slug": "medical-italian",
    "name": "Medical Italian",
    "description": "Italian language for healthcare settings",
    "icon": "languages",
    "color": "green",
    "sortOrder": 300
  }
];

export const flashcardDecks: FlashcardDeck[] = [
  {
    "id": 28,
    "slug": "premed-biology-membrane-bound-organelles",
    "title": "Cell Biology: Membrane-Bound Organelles",
    "description": "Master the structure and function of mitochondria, ER, Golgi, lysosomes, peroxisomes, and vacuoles with high-yield comparisons.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 70,
    "isVerified": false,
    "createdAt": "2026-01-05T07:09:37.699Z",
    "updatedAt": "2026-01-05T18:45:29.288Z"
  },
  {
    "id": 29,
    "slug": "premed-biology-cytoskeleton",
    "title": "Cell Biology: Cytoskeleton",
    "description": "Microfilaments, intermediate filaments, and microtubules. Motor proteins, cell movement, and structural support explained.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 80,
    "isVerified": false,
    "createdAt": "2026-01-05T08:22:25.653Z",
    "updatedAt": "2026-01-05T18:45:29.316Z"
  },
  {
    "id": 30,
    "slug": "premed-biology-prokaryotes-vs-eukaryotes",
    "title": "Cell Biology: Prokaryotes vs Eukaryotes",
    "description": "Compare prokaryotic and eukaryotic cells. Ribosomes, membranes, DNA organization, and classic exam traps.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 110,
    "isVerified": false,
    "createdAt": "2026-01-05T08:39:30.942Z",
    "updatedAt": "2026-01-05T18:45:29.364Z"
  },
  {
    "id": 31,
    "slug": "premed-biology-viruses",
    "title": "Microbiology: Viruses",
    "description": "Viral structure, replication cycles, lytic vs lysogenic pathways, and key virus concepts for pre-med exams.",
    "tags": [
      "exam-track:premed",
      "exam-track:premed:biology",
      "topic:virology"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 150,
    "authorDisplayName": "Ari Horesh",
    "isVerified": true,
    "createdAt": "2026-01-05T09:07:38.098Z",
    "updatedAt": "2026-01-05T18:45:29.388Z"
  },
  {
    "id": 32,
    "slug": "premed-cellbio-mitosis",
    "title": "Cell Biology: Mitosis & Cell Cycle",
    "description": "Cell cycle phases, mitotic stages, checkpoints, and chromosome behavior during cell division.",
    "tags": [
      "exam-track:premed",
      "exam-track:premed:biology",
      "topic:virology"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 110,
    "authorDisplayName": "Ari Horesh",
    "isVerified": true,
    "createdAt": "2026-01-05T09:32:02.942Z",
    "updatedAt": "2026-01-05T18:45:29.410Z"
  },
  {
    "id": 33,
    "slug": "premed-cellbio-meiosis",
    "title": "Cell Biology: Meiosis & Genetic Variation",
    "description": "Meiosis I and II, crossing over, independent assortment, and comparisons with mitosis.",
    "tags": [
      "exam-track:premed",
      "exam-track:premed:biology",
      "topic:virology"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 125,
    "authorDisplayName": "Ari Horesh",
    "isVerified": true,
    "createdAt": "2026-01-05T09:45:35.549Z",
    "updatedAt": "2026-01-05T18:45:29.433Z"
  },
  {
    "id": 34,
    "slug": "premed-biology-dna-replication",
    "title": "Molecular Biology: DNA Replication",
    "description": "Replication machinery, leading and lagging strands, Okazaki fragments, and the S phase of the cell cycle.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 120,
    "isVerified": false,
    "createdAt": "2026-01-05T10:14:00.494Z",
    "updatedAt": "2026-01-05T18:45:29.475Z"
  },
  {
    "id": 35,
    "slug": "premed-biology-cell-membrane",
    "title": "Cell Biology: Membrane Structure & Transport",
    "description": "Fluid mosaic model, membrane fluidity, receptors, channels, and transport mechanisms. Active vs passive transport.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 120,
    "isVerified": false,
    "createdAt": "2026-01-05T10:38:58.943Z",
    "updatedAt": "2026-01-05T18:45:29.455Z"
  },
  {
    "id": 36,
    "slug": "premed-biology-glucose-metabolism",
    "title": "Metabolism: Glucose & Hormonal Control",
    "description": "Glycolysis, pyruvate fates, lactate fermentation, and blood glucose regulation by insulin and glucagon.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 120,
    "isVerified": false,
    "createdAt": "2026-01-05T11:00:17.674Z",
    "updatedAt": "2026-01-05T18:45:29.520Z"
  },
  {
    "id": 37,
    "slug": "premed-biology-hemoglobin-bohr",
    "title": "Physiology: Hemoglobin & O₂ Transport",
    "description": "Oxygen-hemoglobin binding, cooperativity, Bohr effect, fetal hemoglobin, myoglobin, and CO poisoning.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 110,
    "isVerified": false,
    "createdAt": "2026-01-05T11:13:15.627Z",
    "updatedAt": "2026-01-05T18:45:29.608Z"
  },
  {
    "id": 38,
    "slug": "premed-biology-intro-physiology-tissues",
    "title": "Physiology: Tissues & Homeostasis",
    "description": "The four tissue types, homeostasis, and feedback loops. Foundation for organ system physiology.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:easy"
    ],
    "difficultyLevel": "easy",
    "cardCount": 141,
    "isVerified": false,
    "createdAt": "2026-01-05T11:38:28.218Z",
    "updatedAt": "2026-01-05T18:45:29.586Z"
  },
  {
    "id": 39,
    "slug": "premed-biology-neurons-action-potentials",
    "title": "Neurophysiology: Neurons & Synapses",
    "description": "Neuron structure, resting potential, action potentials, ion channels, synapses, and neurotransmitters.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 154,
    "isVerified": false,
    "createdAt": "2026-01-05T11:55:15.012Z",
    "updatedAt": "2026-01-05T18:45:29.651Z"
  },
  {
    "id": 40,
    "slug": "premed-biology-blood-buffers-acid-base",
    "title": "Physiology: Acid-Base Balance",
    "description": "pH regulation, bicarbonate buffer system, respiratory and metabolic disorders, and compensation mechanisms.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 130,
    "isVerified": false,
    "createdAt": "2026-01-05T12:15:10.230Z",
    "updatedAt": "2026-01-05T18:45:29.630Z"
  },
  {
    "id": 41,
    "slug": "premed-biology-immunology-vaccines",
    "title": "Immunology: Immune Responses & Vaccines",
    "description": "Innate vs adaptive immunity, B and T cells, antibodies, vaccines, and lymphoid organ functions.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 160,
    "isVerified": false,
    "createdAt": "2026-01-05T12:32:32.014Z",
    "updatedAt": "2026-01-05T18:45:29.739Z"
  },
  {
    "id": 42,
    "slug": "premed-biology-blood-pressure-regulation",
    "title": "Cardiovascular: Blood Pressure Regulation",
    "description": "BP equations, baroreceptor reflex, RAAS system, autonomic control, and vessel physiology.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 146,
    "isVerified": false,
    "createdAt": "2026-01-05T12:51:15.181Z",
    "updatedAt": "2026-01-05T18:45:29.716Z"
  },
  {
    "id": 43,
    "slug": "premed-biology-bone-growth-marrow",
    "title": "Musculoskeletal: Bone & Growth",
    "description": "Bone structure, osteoblasts, osteoclasts, growth plates, bone marrow, and calcium homeostasis.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 146,
    "isVerified": false,
    "createdAt": "2026-01-05T13:08:53.229Z",
    "updatedAt": "2026-01-05T18:45:29.804Z"
  },
  {
    "id": 44,
    "slug": "premed-biology-brain-anatomy-functions",
    "title": "Neuroanatomy: Brain Structure & Function",
    "description": "Cerebral lobes, motor and sensory cortex, Broca and Wernicke areas, limbic system, brainstem, and cerebellum.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 165,
    "isVerified": false,
    "createdAt": "2026-01-05T13:25:19.810Z",
    "updatedAt": "2026-01-05T18:45:29.672Z"
  },
  {
    "id": 45,
    "slug": "premed-biology-macromolecules-nutrition",
    "title": "Biochemistry: Macromolecules & Nutrition",
    "description": "Carbohydrates, lipids, proteins, nucleic acids, vitamins, minerals, and essential nutrient concepts.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:easy"
    ],
    "difficultyLevel": "easy",
    "cardCount": 199,
    "isVerified": false,
    "createdAt": "2026-01-05T13:44:00.462Z",
    "updatedAt": "2026-01-05T18:45:29.760Z"
  },
  {
    "id": 46,
    "slug": "premed-biology-gi-physiology-digestion",
    "title": "Digestive System: GI Physiology",
    "description": "GI anatomy, mechanical and chemical digestion, bile, pancreatic enzymes, GI hormones, and absorption.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 209,
    "isVerified": false,
    "createdAt": "2026-01-05T14:08:31.375Z",
    "updatedAt": "2026-01-05T18:45:29.782Z"
  },
  {
    "id": 47,
    "slug": "premed-biology-cardiac-cycle-conduction",
    "title": "Cardiovascular: Heart & Cardiac Cycle",
    "description": "Heart anatomy, valves, blood flow, cardiac cycle phases, conduction system, ECG waves, and hemodynamics.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 210,
    "isVerified": false,
    "createdAt": "2026-01-05T14:32:40.500Z",
    "updatedAt": "2026-01-05T18:45:29.694Z"
  },
  {
    "id": 48,
    "slug": "premed-biology-central-dogma",
    "title": "Molecular Biology: Central Dogma",
    "description": "DNA → RNA → Protein. Transcription, translation, genetic code, RNA processing, and gene regulation.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 211,
    "isVerified": false,
    "createdAt": "2026-01-05T14:59:53.511Z",
    "updatedAt": "2026-01-05T18:45:29.496Z"
  },
  {
    "id": 49,
    "slug": "premed-biology-photosynthesis",
    "title": "Plant Biology: Photosynthesis",
    "description": "Light reactions, Calvin cycle, chloroplast structure, stomata, limiting factors, and C3/C4/CAM comparisons.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 190,
    "isVerified": false,
    "createdAt": "2026-01-05T15:20:13.501Z",
    "updatedAt": "2026-01-05T18:45:29.564Z"
  },
  {
    "id": 50,
    "slug": "premed-biology-mitochondria-respiration",
    "title": "Metabolism: Cellular Respiration",
    "description": "Mitochondria structure, glycolysis, pyruvate oxidation, Krebs cycle, ETC, and oxidative phosphorylation.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 211,
    "isVerified": false,
    "createdAt": "2026-01-05T15:47:07.850Z",
    "updatedAt": "2026-01-05T18:45:29.542Z"
  },
  {
    "id": 51,
    "slug": "premed-biology-evolution-selection-drift",
    "title": "Evolution: Selection, Drift & Speciation",
    "description": "Natural selection, genetic drift, gene flow, speciation, reproductive isolation, and phylogeny.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 213,
    "isVerified": false,
    "createdAt": "2026-01-05T16:20:25.746Z",
    "updatedAt": "2026-01-05T18:45:29.872Z"
  },
  {
    "id": 52,
    "slug": "premed-biology-female-reproductive-cycle",
    "title": "Reproduction: Female Cycle & Hormones",
    "description": "Female anatomy, HPO axis, ovarian and uterine cycles, ovulation, fertilization, implantation, and oogenesis.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 196,
    "isVerified": false,
    "createdAt": "2026-01-05T17:35:33.013Z",
    "updatedAt": "2026-01-05T18:45:29.827Z"
  },
  {
    "id": 53,
    "slug": "premed-biology-male-reproductive-system",
    "title": "Reproduction: Male System & Hormones",
    "description": "Male anatomy, spermatogenesis, HPG axis, testosterone, accessory glands, and sperm structure.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 200,
    "isVerified": false,
    "createdAt": "2026-01-05T18:03:05.437Z",
    "updatedAt": "2026-01-05T18:45:29.849Z"
  },
  {
    "id": 54,
    "slug": "premed-biology-kidney-nephron",
    "title": "Renal Physiology: Kidney & Nephron",
    "description": "Nephron anatomy, glomerular filtration, reabsorption and secretion, loop of Henle, ADH, aldosterone, RAAS, acid-base regulation, and urinalysis.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 212,
    "isVerified": false,
    "createdAt": "2026-01-05T18:51:05.809Z",
    "updatedAt": "2026-01-05T18:51:05.809Z"
  },
  {
    "id": 55,
    "slug": "premed-biology-endocrine-system",
    "title": "Endocrine System: Pituitary, Thyroid & Adrenal",
    "description": "Hormone classes, hypothalamic-pituitary axes, thyroid and parathyroid hormones, adrenal cortex and medulla, pancreatic hormones, feedback loops, and clinical patterns.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 230,
    "isVerified": false,
    "createdAt": "2026-01-06T05:59:05.123Z",
    "updatedAt": "2026-01-06T05:59:05.123Z"
  },
  {
    "id": 56,
    "slug": "premed-biology-muscle-contraction",
    "title": "Muscle Physiology: Skeletal Muscle Contraction",
    "description": "Sarcomere structure, neuromuscular junction, excitation-contraction coupling, cross-bridge cycle, ATP requirements, force control, motor units, fiber types, and muscle metabolism.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 211,
    "isVerified": false,
    "createdAt": "2026-01-06T06:24:43.496Z",
    "updatedAt": "2026-01-06T06:24:43.496Z"
  },
  {
    "id": 57,
    "slug": "premed-biology-vision-eye",
    "title": "Sensory Physiology: Vision, Rods & Cones",
    "description": "Retina structure, photoreceptors (rods vs cones), phototransduction cascade, rhodopsin and visual cycle, color vision, night vision, dark adaptation, and vitamin A.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 162,
    "isVerified": false,
    "createdAt": "2026-01-06T06:41:29.036Z",
    "updatedAt": "2026-01-06T06:41:29.036Z"
  },
  {
    "id": 58,
    "slug": "premed-biology-taste-smell",
    "title": "Sensory Physiology: Taste & Smell",
    "description": "Taste buds and papillae, five basic tastes, taste transduction, olfactory epithelium and receptors, cranial nerves VII/IX/X/I, smell pathways, flavor perception, and chemosensory disorders.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 175,
    "isVerified": false,
    "createdAt": "2026-01-06T07:29:29.838Z",
    "updatedAt": "2026-01-06T07:29:29.838Z"
  },
  {
    "id": 59,
    "slug": "premed-biology-endomembrane-system",
    "title": "Cell Biology: Endomembrane System",
    "description": "Nuclear envelope, rough and smooth ER, Golgi apparatus, vesicle trafficking, protein targeting and signal peptides, lysosomes, endocytosis and exocytosis, and membrane topology.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 189,
    "isVerified": false,
    "createdAt": "2026-01-06T08:18:18.324Z",
    "updatedAt": "2026-01-06T08:18:18.324Z"
  },
  {
    "id": 60,
    "slug": "premed-biology-enzyme-kinetics",
    "title": "Biochemistry: Enzyme Kinetics & Inhibition",
    "description": "Michaelis-Menten kinetics, Km and Vmax, competitive, noncompetitive, uncompetitive, mixed and irreversible inhibition, Lineweaver-Burk plots, allosteric enzymes, and exam calculations.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 159,
    "isVerified": false,
    "createdAt": "2026-01-06T08:51:07.010Z",
    "updatedAt": "2026-01-06T08:51:07.010Z"
  },
  {
    "id": 61,
    "slug": "premed-biology-vascular-system",
    "title": "Cardiovascular: Vascular System & Portal Circulation",
    "description": "Arteries, veins, capillaries, vessel wall layers, hemodynamics, resistance vessels, capillary exchange pressures, hepatic and hypothalamic-pituitary portal systems, kidney microcirculation, and venous return.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 176,
    "isVerified": false,
    "createdAt": "2026-01-06T09:12:54.894Z",
    "updatedAt": "2026-01-06T09:12:54.894Z"
  },
  {
    "id": 62,
    "slug": "premed-biology-semen-sperm",
    "title": "Reproduction: Semen Production & Sperm Maturation",
    "description": "Spermatogenesis, seminiferous tubules, Sertoli and Leydig cells, LH/FSH/testosterone/inhibin, sperm pathway, seminal vesicles, prostate, bulbourethral glands, capacitation, and clinical scenarios.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 154,
    "isVerified": false,
    "createdAt": "2026-01-06T09:56:41.565Z",
    "updatedAt": "2026-01-06T09:56:41.565Z"
  },
  {
    "id": 63,
    "slug": "premed-biology-genetics-pedigrees",
    "title": "Genetics: Pedigrees, Mendel & Inheritance Traps",
    "description": "Mendelian laws, monohybrid and dihybrid crosses, Punnett squares, probability, incomplete dominance, codominance, ABO blood types, X-linked/Y-linked/mitochondrial inheritance, pedigree analysis, and common exam traps.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 188,
    "isVerified": false,
    "createdAt": "2026-01-06T11:54:01.533Z",
    "updatedAt": "2026-01-06T11:54:01.533Z"
  },
  {
    "id": 64,
    "slug": "premed-chemistry-stoichiometry",
    "title": "Stoichiometry: Molar Masses, Formulas & Calculations",
    "description": "Moles, Avogadro's number, atomic/molar masses of 50+ compounds, diatomic elements, polyatomic ions, formula writing, limiting reagents, percent yield, molarity, dilution, gas laws, and empirical vs molecular formulas.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 193,
    "isVerified": false,
    "createdAt": "2026-01-07T08:29:31.799Z",
    "updatedAt": "2026-01-07T08:29:31.799Z"
  },
  {
    "id": 65,
    "slug": "premed-chemistry-periodic-table",
    "title": "Periodic Table: Groups, Trends & Atomic Numbers",
    "description": "Groups, periods, blocks (s/p/d/f), atomic numbers of 40+ elements, periodic trends (atomic radius, ionization energy, electronegativity, metallic character), valence electrons, ion formation, and common exam traps.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 218,
    "isVerified": false,
    "createdAt": "2026-01-07T08:52:14.037Z",
    "updatedAt": "2026-01-07T08:52:14.037Z"
  },
  {
    "id": 66,
    "slug": "premed-chemistry-vsepr",
    "title": "VSEPR: Molecular Geometry, Angles & Exceptions",
    "description": "VSEPR theory, electron domains, AXE notation, ideal bond angles, lone pair effects, trigonal bipyramidal/octahedral shapes, expanded octet exceptions, hybridization, and shapes for 40+ common molecules.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 170,
    "isVerified": false,
    "createdAt": "2026-01-07T10:06:27.946Z",
    "updatedAt": "2026-01-07T10:06:27.946Z"
  },
  {
    "id": 67,
    "slug": "premed-chemistry-equilibrium",
    "title": "Chemical Equilibrium: K, Q & Le Chatelier",
    "description": "Equilibrium basics, K expressions, Kc vs Kp, heterogeneous equilibria, reaction quotient Q, Le Chatelier's principle (concentration, pressure, temperature, catalysts), manipulating K, ICE tables, and industrial processes.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 117,
    "isVerified": false,
    "createdAt": "2026-01-07T10:53:04.172Z",
    "updatedAt": "2026-01-07T10:53:04.172Z"
  },
  {
    "id": 68,
    "slug": "premed-chemistry-gas-laws",
    "title": "Gas Laws: PV=nRT, Dalton, Graham & Tricks",
    "description": "Ideal gas law (PV=nRT), units, R values, STP, Boyle's/Charles'/Gay-Lussac's/Combined/Avogadro's laws, Dalton's law, mole fractions, gas over water, gas density, gas stoichiometry, kinetic theory, Graham's law, and ideal vs real gases.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 160,
    "isVerified": false,
    "createdAt": "2026-01-07T12:41:17.335Z",
    "updatedAt": "2026-01-07T12:41:17.335Z"
  },
  {
    "id": 69,
    "slug": "premed-chemistry-kinetics",
    "title": "Reaction Rates & Kinetics: Rate Laws, Ea & Mechanisms",
    "description": "Rate basics, collision theory, activation energy, energy diagrams, factors affecting rate, rate laws, reaction orders, determining order from data, k units, integrated rate laws, half-life, Arrhenius equation, mechanisms, and rate-determining step.",
    "tags": [
      "premed",
      "exam-track:premed",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 158,
    "isVerified": false,
    "createdAt": "2026-01-07T14:25:59.754Z",
    "updatedAt": "2026-01-07T14:25:59.754Z"
  },
  {
    "id": 70,
    "slug": "italian-lesson-1-signora-cia",
    "title": "Medical Italian: Signora Cia",
    "description": "Italian medical vocabulary and clinical phrases from Lesson 1: Signora Cia. 31 terms covering ward rounds, clinical exams, and patient communication.",
    "categoryId": 17,
    "tags": [
      "medical-italian",
      "clinical-italian",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 31,
    "isVerified": true,
    "createdAt": "2026-02-20T06:41:58.735Z",
    "updatedAt": "2026-02-20T06:41:58.735Z"
  },
  {
    "id": 71,
    "slug": "italian-lesson-2-signor-arto",
    "title": "Medical Italian: Signor Arto",
    "description": "Italian medical vocabulary and clinical phrases from Lesson 2: Signor Arto. 22 terms covering ward rounds, clinical exams, and patient communication.",
    "categoryId": 17,
    "tags": [
      "medical-italian",
      "clinical-italian",
      "difficulty:intermediate"
    ],
    "difficultyLevel": "intermediate",
    "cardCount": 22,
    "isVerified": true,
    "createdAt": "2026-02-20T06:41:58.735Z",
    "updatedAt": "2026-02-20T06:41:58.735Z"
  }
];
