// Auto-generated by scripts/pull-db-content.mjs — do not edit manually
import type { PracticeCategory, PracticeQuestionDeck } from "@/types/practice-questions";

export const practiceCategories: PracticeCategory[] = [
  {
    "id": 28,
    "slug": "respiratory",
    "name": "Respiratory Physiology",
    "parentId": 8,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 29,
    "slug": "endocrine",
    "name": "Endocrine System",
    "parentId": 8,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 30,
    "slug": "musculoskeletal",
    "name": "Musculoskeletal System",
    "parentId": 8,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 31,
    "slug": "blood",
    "name": "Blood & Hemoglobin",
    "parentId": 8,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 32,
    "slug": "reproductive",
    "name": "Reproductive System",
    "parentId": 8,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 33,
    "slug": "sensory-systems",
    "name": "Sensory Systems",
    "parentId": 9,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 34,
    "slug": "reflexes",
    "name": "Reflexes & Spinal Cord",
    "parentId": 9,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 35,
    "slug": "chromosomal-disorders",
    "name": "Chromosomal Disorders",
    "parentId": 7,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 36,
    "slug": "gene-regulation",
    "name": "Gene Expression & Regulation",
    "parentId": 7,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 37,
    "slug": "population-genetics",
    "name": "Population Genetics",
    "parentId": 7,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 38,
    "slug": "ecology",
    "name": "Ecology",
    "parentId": 1,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 39,
    "slug": "microbiology",
    "name": "Microbiology",
    "parentId": 1,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 40,
    "slug": "development",
    "name": "Embryology & Development",
    "parentId": 1,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 41,
    "slug": "plant-biology",
    "name": "Plant Biology",
    "parentId": 1,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 42,
    "slug": "biochemistry",
    "name": "Biochemistry",
    "parentId": 1,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 43,
    "slug": "biotechnology",
    "name": "Biotechnology",
    "parentId": 1,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 44,
    "slug": "metabolism",
    "name": "Metabolism",
    "parentId": 42,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 45,
    "slug": "vascular",
    "name": "Vascular System",
    "parentId": 8,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 46,
    "slug": "vision",
    "name": "Vision",
    "parentId": 33,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 47,
    "slug": "enzymology",
    "name": "Enzymology",
    "parentId": 42,
    "depth": 0,
    "sortOrder": 0
  },
  {
    "id": 1,
    "slug": "biology",
    "name": "Biology",
    "description": "Life sciences including cell biology, genetics, physiology, and more",
    "depth": 0,
    "sortOrder": 1,
    "icon": "🧬"
  },
  {
    "id": 5,
    "slug": "cell-biology",
    "name": "Cell Biology",
    "description": "Structure and function of cells",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 1,
    "icon": "🔬"
  },
  {
    "id": 12,
    "slug": "cell-organelles",
    "name": "Cell Organelles",
    "description": "Mitochondria, nucleus, ER, Golgi, and more",
    "parentId": 5,
    "depth": 2,
    "sortOrder": 1,
    "icon": "🔋"
  },
  {
    "id": 15,
    "slug": "dna-replication",
    "name": "DNA Replication",
    "description": "DNA synthesis and the cell cycle",
    "parentId": 6,
    "depth": 2,
    "sortOrder": 1,
    "icon": "🔄"
  },
  {
    "id": 17,
    "slug": "mendelian",
    "name": "Mendelian Genetics",
    "description": "Laws of inheritance and Punnett squares",
    "parentId": 7,
    "depth": 2,
    "sortOrder": 1,
    "icon": "📊"
  },
  {
    "id": 19,
    "slug": "cardiac",
    "name": "Cardiac Physiology",
    "description": "Heart function and the cardiac cycle",
    "parentId": 8,
    "depth": 2,
    "sortOrder": 1,
    "icon": "❤️"
  },
  {
    "id": 23,
    "slug": "brain-anatomy",
    "name": "Brain Anatomy",
    "description": "Brain regions and their functions",
    "parentId": 9,
    "depth": 2,
    "sortOrder": 1,
    "icon": "🧠"
  },
  {
    "id": 26,
    "slug": "natural-selection",
    "name": "Natural Selection",
    "description": "Mechanisms of evolutionary change",
    "parentId": 11,
    "depth": 2,
    "sortOrder": 1,
    "icon": "🎯"
  },
  {
    "id": 49,
    "slug": "atomic-structure",
    "name": "Atomic Structure",
    "description": "Atoms, isotopes, electrons, orbitals, and electron configuration",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 1,
    "icon": "⚛️"
  },
  {
    "id": 63,
    "slug": "mechanics",
    "name": "Mechanics",
    "description": "Motion, forces, Newton's laws, momentum, work, energy, power",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 1,
    "icon": "⚙️"
  },
  {
    "id": 78,
    "slug": "statistics-probability",
    "name": "Statistics and Probability",
    "description": "Probability theory, descriptive and inferential statistics, experimental design",
    "parentId": 77,
    "depth": 1,
    "sortOrder": 1,
    "icon": "📊"
  },
  {
    "id": 79,
    "slug": "logic-probability",
    "name": "Probability",
    "description": "Probability word problems and reasoning",
    "parentId": 4,
    "depth": 1,
    "sortOrder": 1,
    "icon": "🎲"
  },
  {
    "id": 2,
    "slug": "chemistry",
    "name": "Chemistry",
    "description": "General, organic, and inorganic chemistry",
    "depth": 0,
    "sortOrder": 2,
    "icon": "⚗️"
  },
  {
    "id": 6,
    "slug": "molecular-biology",
    "name": "Molecular Biology",
    "description": "DNA, RNA, and protein synthesis",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 2,
    "icon": "🧫"
  },
  {
    "id": 13,
    "slug": "cell-division",
    "name": "Cell Division",
    "description": "Mitosis and meiosis",
    "parentId": 5,
    "depth": 2,
    "sortOrder": 2,
    "icon": "➗"
  },
  {
    "id": 16,
    "slug": "protein-synthesis",
    "name": "Protein Synthesis",
    "description": "Transcription and translation",
    "parentId": 6,
    "depth": 2,
    "sortOrder": 2,
    "icon": "🏭"
  },
  {
    "id": 18,
    "slug": "pedigrees",
    "name": "Pedigrees",
    "description": "Family tree analysis and inheritance patterns",
    "parentId": 7,
    "depth": 2,
    "sortOrder": 2,
    "icon": "👨‍👩‍👧‍👦"
  },
  {
    "id": 20,
    "slug": "renal",
    "name": "Renal Physiology",
    "description": "Kidney function and nephron structure",
    "parentId": 8,
    "depth": 2,
    "sortOrder": 2,
    "icon": "🫘"
  },
  {
    "id": 24,
    "slug": "action-potentials",
    "name": "Action Potentials",
    "description": "Neurons and neurotransmission",
    "parentId": 9,
    "depth": 2,
    "sortOrder": 2,
    "icon": "⚡"
  },
  {
    "id": 27,
    "slug": "speciation",
    "name": "Speciation",
    "description": "Formation of new species",
    "parentId": 11,
    "depth": 2,
    "sortOrder": 2,
    "icon": "🌳"
  },
  {
    "id": 50,
    "slug": "periodic-table",
    "name": "Periodic Table & Trends",
    "description": "Periodic table organization and trends (radius, IE, EN, reactivity)",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 2,
    "icon": "📊"
  },
  {
    "id": 64,
    "slug": "kinematics",
    "name": "Kinematics",
    "description": "1D/2D motion, velocity, acceleration, projectile motion, graphs",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 2,
    "icon": "📈"
  },
  {
    "id": 3,
    "slug": "physics",
    "name": "Physics",
    "description": "Mechanics, thermodynamics, electricity, and more",
    "depth": 0,
    "sortOrder": 3,
    "icon": "⚛️"
  },
  {
    "id": 7,
    "slug": "genetics",
    "name": "Genetics",
    "description": "Inheritance, genes, and genetic variation",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 3,
    "icon": "🧬"
  },
  {
    "id": 14,
    "slug": "cell-membrane",
    "name": "Cell Membrane",
    "description": "Membrane structure and transport",
    "parentId": 5,
    "depth": 2,
    "sortOrder": 3,
    "icon": "🧱"
  },
  {
    "id": 21,
    "slug": "gi",
    "name": "GI Physiology",
    "description": "Digestive system function and enzymes",
    "parentId": 8,
    "depth": 2,
    "sortOrder": 3,
    "icon": "🍽️"
  },
  {
    "id": 25,
    "slug": "ans",
    "name": "Autonomic Nervous System",
    "description": "Sympathetic and parasympathetic systems",
    "parentId": 9,
    "depth": 2,
    "sortOrder": 3,
    "icon": "🔀"
  },
  {
    "id": 51,
    "slug": "chemical-bonding",
    "name": "Chemical Bonding",
    "description": "Ionic/covalent/metallic bonding, Lewis structures, polarity, intermolecular forces",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 3,
    "icon": "🔗"
  },
  {
    "id": 65,
    "slug": "forces-dynamics",
    "name": "Forces & Dynamics",
    "description": "Newton's laws, friction, tension, normal force, free-body diagrams",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 3,
    "icon": "💪"
  },
  {
    "id": 4,
    "slug": "logic",
    "name": "Logic & Problem Solving",
    "description": "Critical thinking, reasoning, and problem-solving skills",
    "depth": 0,
    "sortOrder": 4,
    "icon": "🧩"
  },
  {
    "id": 8,
    "slug": "physiology",
    "name": "Physiology",
    "description": "Function of organ systems",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 4,
    "icon": "❤️"
  },
  {
    "id": 22,
    "slug": "tissues",
    "name": "Tissues",
    "description": "Tissue types and organization",
    "parentId": 8,
    "depth": 2,
    "sortOrder": 4,
    "icon": "🧫"
  },
  {
    "id": 52,
    "slug": "chemical-reactions-stoichiometry",
    "name": "Chemical Reactions & Stoichiometry",
    "description": "Balancing equations, mole concept, limiting reagents, yields, and reaction types",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 4,
    "icon": "⚖️"
  },
  {
    "id": 66,
    "slug": "work-energy-power",
    "name": "Work, Energy & Power",
    "description": "Work-energy theorem, kinetic/potential energy, conservation, power",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 4,
    "icon": "⚡"
  },
  {
    "id": 9,
    "slug": "neuroscience",
    "name": "Neuroscience",
    "description": "Nervous system structure and function",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 5,
    "icon": "🧠"
  },
  {
    "id": 53,
    "slug": "states-of-matter-gases",
    "name": "States of Matter & Gases",
    "description": "Solids/liquids/gases, phase changes, kinetic theory, gas laws",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 5,
    "icon": "💨"
  },
  {
    "id": 67,
    "slug": "momentum-collisions",
    "name": "Momentum & Collisions",
    "description": "Linear momentum, impulse, conservation, elastic/inelastic collisions",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 5,
    "icon": "💥"
  },
  {
    "id": 10,
    "slug": "immunology",
    "name": "Immunology",
    "description": "Immune system and defense mechanisms",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 6,
    "icon": "🛡️"
  },
  {
    "id": 54,
    "slug": "solutions",
    "name": "Solutions & Concentration",
    "description": "Solubility, molarity, dilutions, colligative ideas (basic), mixtures",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 6,
    "icon": "🧪"
  },
  {
    "id": 68,
    "slug": "circular-motion",
    "name": "Circular Motion",
    "description": "Centripetal force/acceleration, orbital motion, banked curves",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 6,
    "icon": "🔄"
  },
  {
    "id": 11,
    "slug": "evolution",
    "name": "Evolution",
    "description": "Natural selection, speciation, and evolutionary biology",
    "parentId": 1,
    "depth": 1,
    "sortOrder": 7,
    "icon": "🦎"
  },
  {
    "id": 55,
    "slug": "acids-bases-ph",
    "name": "Acids, Bases & pH",
    "description": "pH/pOH, strong vs weak acids/bases, buffers (basic), titrations",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 7,
    "icon": "🧫"
  },
  {
    "id": 69,
    "slug": "gravitation",
    "name": "Gravitation",
    "description": "Newton's law of gravitation, gravitational fields, orbits",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 7,
    "icon": "🌍"
  },
  {
    "id": 56,
    "slug": "chemical-equilibrium",
    "name": "Chemical Equilibrium",
    "description": "Le Chatelier’s principle, equilibrium constants (K), Ka/Kb/Ksp (intro)",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 8,
    "icon": "🔄"
  },
  {
    "id": 70,
    "slug": "oscillations-waves",
    "name": "Oscillations & Waves",
    "description": "SHM, pendulums, wave properties, standing waves, sound",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 8,
    "icon": "🌊"
  },
  {
    "id": 57,
    "slug": "chemical-kinetics",
    "name": "Chemical Kinetics",
    "description": "Reaction rates, factors affecting rate, activation energy, catalysts",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 9,
    "icon": "⏱️"
  },
  {
    "id": 71,
    "slug": "electricity",
    "name": "Electricity",
    "description": "Charge, current, voltage, resistance, Ohm's law, circuits",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 9,
    "icon": "🔌"
  },
  {
    "id": 58,
    "slug": "thermochemistry",
    "name": "Thermochemistry",
    "description": "Endothermic/exothermic processes, enthalpy, calorimetry (intro)",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 10,
    "icon": "🔥"
  },
  {
    "id": 72,
    "slug": "magnetism",
    "name": "Magnetism",
    "description": "Magnetic fields, electromagnets, motors, electromagnetic induction",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 10,
    "icon": "🧲"
  },
  {
    "id": 59,
    "slug": "redox-electrochemistry",
    "name": "Redox & Electrochemistry",
    "description": "Oxidation numbers, redox reactions, galvanic cells, electrolysis (intro)",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 11,
    "icon": "🔋"
  },
  {
    "id": 73,
    "slug": "thermodynamics",
    "name": "Thermodynamics",
    "description": "Heat, temperature, specific heat, thermal expansion, gas laws",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 11,
    "icon": "🌡️"
  },
  {
    "id": 60,
    "slug": "organic-chemistry",
    "name": "Organic Chemistry",
    "description": "Hydrocarbons, functional groups, isomerism, polymers, basic reactions",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 12,
    "icon": "🧬"
  },
  {
    "id": 74,
    "slug": "optics",
    "name": "Optics",
    "description": "Reflection, refraction, lenses, mirrors, wave optics",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 12,
    "icon": "🔍"
  },
  {
    "id": 61,
    "slug": "nuclear-chemistry",
    "name": "Nuclear Chemistry",
    "description": "Radioactivity, nuclear decay, half-life, basic nuclear equations",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 13,
    "icon": "☢️"
  },
  {
    "id": 75,
    "slug": "modern-physics",
    "name": "Modern Physics",
    "description": "Atomic structure, nuclear physics, radioactivity, quantum basics",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 13,
    "icon": "⚛️"
  },
  {
    "id": 62,
    "slug": "analytical-lab-techniques",
    "name": "Analytical & Lab Techniques",
    "description": "Basic separation/analysis: chromatography, spectroscopy concepts, lab skills",
    "parentId": 2,
    "depth": 1,
    "sortOrder": 14,
    "icon": "🔎"
  },
  {
    "id": 76,
    "slug": "fluids",
    "name": "Fluids & Pressure",
    "description": "Density, pressure, buoyancy, Bernoulli's principle",
    "parentId": 3,
    "depth": 1,
    "sortOrder": 14,
    "icon": "💧"
  },
  {
    "id": 77,
    "slug": "math",
    "name": "Mathematics",
    "description": "Mathematical reasoning, statistics, probability, and logic",
    "depth": 0,
    "sortOrder": 200,
    "icon": "📐"
  }
];

export const practiceDecks: PracticeQuestionDeck[] = [
  {
    "id": 1,
    "slug": "premed-biology-mitochondria",
    "title": "Mitochondria",
    "description": "Pre-Med practice questions about mitochondrial structure, function, and inheritance",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 39,
    "createdAt": "2025-12-11T17:27:14.310Z",
    "updatedAt": "2025-12-11T17:36:02.342Z"
  },
  {
    "id": 2,
    "slug": "premed-biology-nucleus",
    "title": "Nucleus",
    "description": "Pre-Med practice questions about the nucleus, chromatin, and nuclear components",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 8,
    "createdAt": "2025-12-11T17:36:03.731Z",
    "updatedAt": "2025-12-11T17:36:03.731Z"
  },
  {
    "id": 3,
    "slug": "premed-biology-ribosome",
    "title": "Ribosomes",
    "description": "Pre-Med practice questions about ribosome structure, location, and function",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 6,
    "createdAt": "2025-12-11T17:36:04.912Z",
    "updatedAt": "2025-12-11T17:36:04.912Z"
  },
  {
    "id": 4,
    "slug": "premed-biology-endoplasmic-reticulum",
    "title": "Endoplasmic Reticulum",
    "description": "Pre-Med practice questions about rough and smooth endoplasmic reticulum",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 7,
    "createdAt": "2025-12-11T17:36:05.802Z",
    "updatedAt": "2025-12-11T17:36:05.802Z"
  },
  {
    "id": 5,
    "slug": "premed-biology-golgi-apparatus",
    "title": "Golgi Apparatus",
    "description": "Pre-Med practice questions about Golgi structure, function, and protein sorting",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 6,
    "createdAt": "2025-12-11T17:36:06.964Z",
    "updatedAt": "2025-12-11T17:36:06.964Z"
  },
  {
    "id": 6,
    "slug": "premed-biology-lysosome",
    "title": "Lysosomes",
    "description": "Pre-Med practice questions about lysosomal structure and function",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 7,
    "createdAt": "2025-12-11T17:36:07.874Z",
    "updatedAt": "2025-12-11T17:36:07.874Z"
  },
  {
    "id": 7,
    "slug": "premed-biology-peroxisome",
    "title": "Peroxisomes",
    "description": "Pre-Med practice questions about peroxisomal structure, metabolism, and targeting",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 6,
    "createdAt": "2025-12-11T17:36:08.945Z",
    "updatedAt": "2025-12-11T17:36:08.945Z"
  },
  {
    "id": 8,
    "slug": "premed-biology-chloroplast",
    "title": "Chloroplasts",
    "description": "Pre-Med practice questions about chloroplast structure, photosynthesis, and endosymbiosis",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 7,
    "createdAt": "2025-12-11T17:36:09.820Z",
    "updatedAt": "2025-12-11T17:36:09.820Z"
  },
  {
    "id": 9,
    "slug": "premed-biology-cytoskeleton",
    "title": "Cytoskeleton",
    "description": "Pre-Med practice questions about microtubules, microfilaments, and intermediate filaments",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-organelles"
    ],
    "accessTier": "free",
    "categoryIds": [
      12
    ],
    "primaryCategoryId": 12,
    "questionCount": 9,
    "createdAt": "2025-12-11T17:36:10.936Z",
    "updatedAt": "2025-12-11T17:36:10.936Z"
  },
  {
    "id": 10,
    "slug": "premed-biology-mitosis",
    "title": "Mitosis",
    "description": "Challenging Pre-med style questions on mitosis, spindle mechanics, and cytokinesis in plant and animal cells",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-division"
    ],
    "accessTier": "free",
    "categoryIds": [
      13
    ],
    "primaryCategoryId": 13,
    "questionCount": 28,
    "createdAt": "2025-12-11T17:54:24.195Z",
    "updatedAt": "2025-12-11T17:54:24.195Z"
  },
  {
    "id": 11,
    "slug": "premed-biology-meiosis",
    "title": "Meiosis",
    "description": "Challenging Pre-med style questions on meiosis, ploidy, chromatids/DNA molecules, crossing over, segregation, and independent assortment",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-division"
    ],
    "accessTier": "free",
    "categoryIds": [
      13
    ],
    "primaryCategoryId": 13,
    "questionCount": 24,
    "createdAt": "2025-12-11T18:18:12.226Z",
    "updatedAt": "2025-12-11T18:18:12.226Z"
  },
  {
    "id": 12,
    "slug": "premed-biology-mendelian-genetics",
    "title": "Mendelian Genetics",
    "description": "Pre-med style practice questions on Mendelian inheritance, segregation, independent assortment, pedigrees, and probability",
    "tags": [
      "premed",
      "biology",
      "genetics"
    ],
    "accessTier": "free",
    "categoryIds": [
      17
    ],
    "primaryCategoryId": 17,
    "questionCount": 22,
    "createdAt": "2025-12-11T18:29:20.166Z",
    "updatedAt": "2025-12-11T18:29:20.166Z"
  },
  {
    "id": 13,
    "slug": "premed-biology-evolution",
    "title": "Evolution: Selection, Drift, and Speciation",
    "description": "Comprehensive Pre-med style evolution questions on terminology, natural selection, genetic drift, speciation, and sources of variation",
    "tags": [
      "premed",
      "biology",
      "evolution"
    ],
    "accessTier": "free",
    "categoryIds": [
      26
    ],
    "primaryCategoryId": 26,
    "questionCount": 40,
    "createdAt": "2025-12-11T18:37:20.263Z",
    "updatedAt": "2025-12-11T18:37:20.263Z"
  },
  {
    "id": 14,
    "slug": "premed-biology-dna-replication",
    "title": "DNA Replication & S Phase",
    "description": "Comprehensive Pre-med style questions on DNA replication, S phase, enzymes, directionality, and regulation",
    "tags": [
      "premed",
      "biology",
      "molecular-biology"
    ],
    "accessTier": "free",
    "categoryIds": [
      15
    ],
    "primaryCategoryId": 15,
    "questionCount": 30,
    "createdAt": "2025-12-11T18:44:58.617Z",
    "updatedAt": "2025-12-11T18:44:58.617Z"
  },
  {
    "id": 15,
    "slug": "premed-biology-membrane-transport",
    "title": "Cell Membrane & Transport",
    "description": "Pre-med style questions on membrane structure, fluid mosaic model, diffusion, osmosis, active transport, and vesicular transport",
    "tags": [
      "premed",
      "biology",
      "cell-biology"
    ],
    "accessTier": "free",
    "categoryIds": [
      14
    ],
    "primaryCategoryId": 14,
    "questionCount": 30,
    "createdAt": "2025-12-11T18:51:57.757Z",
    "updatedAt": "2025-12-11T18:51:57.757Z"
  },
  {
    "id": 16,
    "slug": "premed-biology-gradients-osmotic-oncotic",
    "title": "Gradients, Osmotic & Oncotic Pressure",
    "description": "Comprehensive Pre-med style questions on gradients, osmotic and oncotic pressure, Starling forces, and physiological examples (edema, capillaries, IV fluids).",
    "tags": [
      "premed",
      "biology",
      "physiology"
    ],
    "accessTier": "free",
    "categoryIds": [
      14
    ],
    "primaryCategoryId": 14,
    "questionCount": 28,
    "createdAt": "2025-12-11T19:00:14.613Z",
    "updatedAt": "2025-12-11T19:00:14.613Z"
  },
  {
    "id": 17,
    "slug": "premed-biology-basic-physiology-tissues",
    "title": "Basic Physiology & Tissue Types",
    "description": "High-school/pre-med-level questions on basic physiology concepts, homeostasis, and the four main tissue types.",
    "tags": [
      "premed",
      "biology",
      "physiology"
    ],
    "accessTier": "free",
    "categoryIds": [
      22
    ],
    "primaryCategoryId": 22,
    "questionCount": 28,
    "createdAt": "2025-12-11T19:24:29.906Z",
    "updatedAt": "2025-12-11T19:24:29.906Z"
  },
  {
    "id": 18,
    "slug": "premed-biology-nephron-physiology",
    "title": "Nephron Structure & Basic Renal Physiology",
    "description": "High-school/pre-med-level questions on nephron anatomy, transport mechanisms, SGLT, glucose handling, medullary gradients and urine concentration.",
    "tags": [
      "premed",
      "biology",
      "renal-physiology"
    ],
    "accessTier": "free",
    "categoryIds": [
      20
    ],
    "primaryCategoryId": 20,
    "questionCount": 35,
    "createdAt": "2025-12-11T19:40:55.941Z",
    "updatedAt": "2025-12-11T19:40:55.941Z"
  },
  {
    "id": 19,
    "slug": "premed-biology-cardiac-cycle",
    "title": "Cardiac Cycle & Basic Cardiac Physiology",
    "description": "High-school/pre-med-level questions on the cardiac cycle, heart sounds, valve events, ECG relationships, and stroke volume.",
    "tags": [
      "premed",
      "biology",
      "cardiac-physiology"
    ],
    "accessTier": "free",
    "categoryIds": [
      19
    ],
    "primaryCategoryId": 19,
    "questionCount": 32,
    "createdAt": "2025-12-11T19:45:24.276Z",
    "updatedAt": "2025-12-11T19:45:24.276Z"
  },
  {
    "id": 20,
    "slug": "premed-biology-sns-vs-psns",
    "title": "Sympathetic vs Parasympathetic Nervous System",
    "description": "High-school/pre-med-level questions comparing the sympathetic and parasympathetic divisions of the autonomic nervous system.",
    "tags": [
      "premed",
      "biology",
      "nervous-system"
    ],
    "accessTier": "free",
    "categoryIds": [
      25
    ],
    "primaryCategoryId": 25,
    "questionCount": 29,
    "createdAt": "2025-12-11T19:57:33.646Z",
    "updatedAt": "2025-12-11T19:57:33.646Z"
  },
  {
    "id": 21,
    "slug": "premed-biology-gi-digestion-hormones",
    "title": "GI Digestion, Enzymes & Hormonal Regulation",
    "description": "High-school/pre-med-level questions on gastrointestinal digestion, key digestive enzymes, and hormonal control (gastrin, secretin, CCK, etc.).",
    "tags": [
      "premed",
      "biology",
      "gi-physiology"
    ],
    "accessTier": "free",
    "categoryIds": [
      21
    ],
    "primaryCategoryId": 21,
    "questionCount": 32,
    "createdAt": "2025-12-11T20:01:30.725Z",
    "updatedAt": "2025-12-11T20:01:30.725Z"
  },
  {
    "id": 22,
    "slug": "premed-biology-brain-basic-anatomy",
    "title": "Brain: Basic Anatomy, Locations & Functions",
    "description": "High-school/pre-med-level questions on major brain regions, lobes, structures and their basic functions.",
    "tags": [
      "premed",
      "biology",
      "neuroscience"
    ],
    "accessTier": "free",
    "categoryIds": [
      23
    ],
    "primaryCategoryId": 23,
    "questionCount": 30,
    "createdAt": "2025-12-11T20:05:06.376Z",
    "updatedAt": "2025-12-11T20:05:06.376Z"
  },
  {
    "id": 23,
    "slug": "premed-biology-genetic-pedigrees",
    "title": "Genetic Pedigrees & Modes of Inheritance",
    "description": "High-school/pre-med-level questions on interpreting pedigrees and identifying modes of inheritance (autosomal vs sex-linked, dominant vs recessive, mitochondrial, and common probability tricks).",
    "tags": [
      "premed",
      "biology",
      "genetics"
    ],
    "accessTier": "free",
    "categoryIds": [
      18
    ],
    "primaryCategoryId": 18,
    "questionCount": 30,
    "createdAt": "2025-12-11T20:15:05.240Z",
    "updatedAt": "2025-12-11T20:15:05.240Z"
  },
  {
    "id": 24,
    "slug": "premed-biology-basic-immunology",
    "title": "Basic Immunology: Concepts for Pre-med/IB",
    "description": "High‑school/pre‑med level questions on innate vs adaptive immunity, cells of the immune system, antibodies, vaccination, inflammation, allergy and autoimmunity.",
    "tags": [
      "premed",
      "biology",
      "immunology"
    ],
    "accessTier": "free",
    "categoryIds": [
      10
    ],
    "primaryCategoryId": 10,
    "questionCount": 28,
    "createdAt": "2025-12-11T20:22:23.950Z",
    "updatedAt": "2025-12-11T20:22:23.950Z"
  },
  {
    "id": 25,
    "slug": "premed-biology-action-potential-neurons",
    "title": "Action Potentials, Neurons & Neurotransmission",
    "description": "High‑school/pre‑med level questions on neuron structure, resting potential, action potentials, synapses, neurotransmitters, and myelination.",
    "tags": [
      "premed",
      "biology",
      "neuroscience"
    ],
    "accessTier": "free",
    "categoryIds": [
      24
    ],
    "primaryCategoryId": 24,
    "questionCount": 32,
    "createdAt": "2025-12-11T20:38:45.575Z",
    "updatedAt": "2025-12-11T20:38:45.575Z"
  },
  {
    "id": 26,
    "slug": "premed-biology-glucose-metabolism",
    "title": "Glucose Metabolism: Glycolysis, Link Reaction, Krebs Cycle & ETC",
    "description": "Pre-med/IB-level practice on cellular respiration from glycolysis (cytosol) to pyruvate oxidation (link reaction), citric acid cycle (Krebs), anaerobic vs aerobic ATP yield, mitochondrial structure, electron transport chain, chemiosmosis, and ATP synthase—focused on concept traps and multi-step reasoning.",
    "tags": [
      "premed",
      "biology",
      "glucose-metabolism",
      "glycolysis",
      "krebs-cycle",
      "etc",
      "atp"
    ],
    "accessTier": "free",
    "categoryIds": [
      44
    ],
    "primaryCategoryId": 44,
    "questionCount": 50,
    "createdAt": "2025-12-11T21:33:37.276Z",
    "updatedAt": "2025-12-12T01:22:22.660Z"
  },
  {
    "id": 27,
    "slug": "premed-biology-glucose-transport-phosphorylation",
    "title": "Glucose Transport & Phosphorylation",
    "description": "Pre-med style questions on glucose entry into cells, GLUT transporters, SGLTs, facilitated diffusion, and phosphorylation by hexokinase and glucokinase.",
    "tags": [
      "premed",
      "biology",
      "glucose",
      "transport",
      "phosphorylation"
    ],
    "accessTier": "free",
    "categoryIds": [
      44
    ],
    "primaryCategoryId": 44,
    "questionCount": 30,
    "createdAt": "2025-12-11T21:44:42.094Z",
    "updatedAt": "2025-12-11T21:44:42.094Z"
  },
  {
    "id": 28,
    "slug": "premed-biology-reflex-arc",
    "title": "Reflex Arcs, Synapses & Peripheral Nerve Anatomy",
    "description": "High-school/Pre-med/IB questions on reflex arc components, synapses, nerve structure, and factors affecting speed of nervous transmission.",
    "tags": [
      "premed",
      "biology",
      "reflex-arc",
      "synapse",
      "nerve-anatomy"
    ],
    "accessTier": "free",
    "categoryIds": [
      34
    ],
    "primaryCategoryId": 34,
    "questionCount": 30,
    "createdAt": "2025-12-11T22:27:14.753Z",
    "updatedAt": "2025-12-11T22:27:14.753Z"
  },
  {
    "id": 29,
    "slug": "premed-biology-hemoglobin-physiology",
    "title": "Hemoglobin Physiology: Bohr Shift, pH, Cooperativity & Sickle Cell",
    "description": "High‑school/Pre-med/IB questions on hemoglobin structure, oxygen binding cooperativity, Bohr shift (CO₂/pH effects), alkalosis/acidosis, fetal hemoglobin, and sickle cell basics.",
    "tags": [
      "premed",
      "biology",
      "hemoglobin",
      "physiology",
      "oxygen-transport"
    ],
    "accessTier": "free",
    "categoryIds": [
      31
    ],
    "primaryCategoryId": 31,
    "questionCount": 30,
    "createdAt": "2025-12-11T22:54:13.049Z",
    "updatedAt": "2025-12-11T22:54:13.049Z"
  },
  {
    "id": 30,
    "slug": "premed-biology-vision-physiology",
    "title": "Vision Physiology",
    "description": "High school / pre-med / IB questions on eye optics, retina and photoreceptors, phototransduction basics, and key visual pathway concepts.",
    "tags": [
      "premed",
      "biology",
      "vision",
      "eye",
      "physiology"
    ],
    "accessTier": "free",
    "categoryIds": [
      46
    ],
    "primaryCategoryId": 46,
    "questionCount": 30,
    "createdAt": "2025-12-11T23:06:00.759Z",
    "updatedAt": "2025-12-11T23:06:00.759Z"
  },
  {
    "id": 31,
    "slug": "premed-biology-vision-phototransduction",
    "title": "Vision: Phototransduction in Rods & Cones",
    "description": "High school / pre-med / IB questions that teach phototransduction: what light does inside rods and cones, the cGMP pathway, neurotransmitter changes, bleaching, adaptation, and key rod/cone differences.",
    "tags": [
      "premed",
      "biology",
      "vision",
      "phototransduction",
      "retina"
    ],
    "accessTier": "free",
    "categoryIds": [
      46
    ],
    "primaryCategoryId": 46,
    "questionCount": 30,
    "createdAt": "2025-12-11T23:21:21.044Z",
    "updatedAt": "2025-12-11T23:21:21.044Z"
  },
  {
    "id": 32,
    "slug": "premed-biology-muscle-contraction",
    "title": "Muscle Contraction, Muscle Tissue & Tendons",
    "description": "60+ Pre-med/IB-style questions on skeletal muscle fiber anatomy, sliding filament theory, excitation-contraction coupling, motor units, energy systems, fiber types, smooth vs cardiac muscle basics, tendons, and biomechanics.",
    "tags": [
      "premed",
      "biology",
      "muscle",
      "physiology",
      "contraction"
    ],
    "accessTier": "free",
    "categoryIds": [
      30
    ],
    "primaryCategoryId": 30,
    "questionCount": 70,
    "createdAt": "2025-12-11T23:40:02.463Z",
    "updatedAt": "2025-12-11T23:40:02.463Z"
  },
  {
    "id": 33,
    "slug": "premed-biology-male-reproduction",
    "title": "Male Reproductive System: Hormones, Anatomy & Spermatogenesis",
    "description": "High school / pre-med / IB practice on the HPG axis, endocrine feedback, testicular anatomy, and spermatogenesis/meiosis (n, chromatids/DNA molecules, stages, and locations).",
    "tags": [
      "premed",
      "biology",
      "male-reproduction",
      "hormones",
      "spermatogenesis"
    ],
    "accessTier": "free",
    "categoryIds": [
      32
    ],
    "primaryCategoryId": 32,
    "questionCount": 100,
    "createdAt": "2025-12-12T00:20:48.350Z",
    "updatedAt": "2025-12-12T00:20:48.350Z"
  },
  {
    "id": 34,
    "slug": "premed-biology-female-reproduction",
    "title": "Female Reproductive System: Hormones, Cycle, Anatomy & Oogenesis",
    "description": "High school / pre-med / IB practice on female reproductive anatomy, ovarian + uterine cycles, endocrine feedback (GnRH–LH/FSH–ovary), oogenesis/meiosis timing (n, chromatids/DNA molecules), ovulation, fertilization, implantation, and key pregnancy/lactation hormones.",
    "tags": [
      "premed",
      "biology",
      "female-reproduction",
      "hormones",
      "oogenesis",
      "menstrual-cycle"
    ],
    "accessTier": "free",
    "categoryIds": [
      32
    ],
    "primaryCategoryId": 32,
    "questionCount": 100,
    "createdAt": "2025-12-12T00:38:16.205Z",
    "updatedAt": "2025-12-12T00:38:16.205Z"
  },
  {
    "id": 35,
    "slug": "premed-biology-vascular-system",
    "title": "Vascular System: Arteries, Veins, Capillaries & Regulation",
    "description": "Pre-med/IB-level practice on vessel anatomy (tunics, valves, compliance), artery vs vein function, capillary types and exchange, portal systems (hepatic and pituitary), and regulation of vascular tone (autonomic, endothelial and hormonal control).",
    "tags": [
      "premed",
      "biology",
      "vascular-system",
      "arteries",
      "veins",
      "capillaries",
      "blood-pressure"
    ],
    "accessTier": "free",
    "categoryIds": [
      45
    ],
    "primaryCategoryId": 45,
    "questionCount": 60,
    "createdAt": "2025-12-12T01:02:34.909Z",
    "updatedAt": "2025-12-12T01:02:34.909Z"
  },
  {
    "id": 36,
    "slug": "premed-biology-photosynthesis",
    "title": "Photosynthesis & Plant Structure",
    "description": "Pre-med/IB-level practice on chloroplast structure, light reactions vs Calvin cycle, chemiosmosis in thylakoids, C3/C4/CAM and photorespiration basics, plus core leaf/vascular anatomy (stomata, mesophyll, xylem, phloem) and limiting factors.",
    "tags": [
      "premed",
      "biology",
      "photosynthesis",
      "chloroplast",
      "calvin-cycle",
      "plant-anatomy"
    ],
    "accessTier": "free",
    "categoryIds": [
      41
    ],
    "primaryCategoryId": 41,
    "questionCount": 50,
    "createdAt": "2025-12-12T01:41:19.471Z",
    "updatedAt": "2025-12-12T01:41:19.471Z"
  },
  {
    "id": 37,
    "slug": "premed-biology-glycolysis-human-cells",
    "title": "Glycolysis in Human Cells & Tissues",
    "description": "Comprehensive Pre-med/IB-style practice on glycolysis fundamentals, regulation, and how different human cell types depend on glycolysis (RBCs, muscle, liver, brain, kidney medulla, lens/cornea, immune cells, cancer). Includes common traps: insulin dependence, NAD+ regeneration, ATP accounting, glycogen vs blood glucose, lactate handling, and lab/clinical-style scenarios.",
    "tags": [
      "premed",
      "biology",
      "glycolysis",
      "cell-types",
      "rbc",
      "muscle",
      "liver",
      "regulation"
    ],
    "accessTier": "free",
    "categoryIds": [
      44
    ],
    "primaryCategoryId": 44,
    "questionCount": 50,
    "createdAt": "2025-12-12T16:47:14.084Z",
    "updatedAt": "2025-12-12T16:47:14.084Z"
  },
  {
    "id": 38,
    "slug": "premed-biology-biotechnology",
    "title": "Biotechnology: DNA Techniques, Cloning, CRISPR, and Bioproducts",
    "description": "IB/Pre-med style biotechnology MCQs covering core lab techniques (PCR, gels, restriction enzymes, cloning, sequencing, blots), genetic engineering (vectors, reporters, selection), CRISPR basics, DNA profiling, and classic applications (recombinant insulin, GM crops, monoclonal antibodies, ELISA). Emphasis on conceptual traps and correct interpretation of results.",
    "tags": [
      "premed",
      "biology",
      "biotechnology",
      "pcr",
      "cloning",
      "crispr",
      "gel-electrophoresis",
      "genetic-engineering"
    ],
    "accessTier": "free",
    "categoryIds": [
      43
    ],
    "primaryCategoryId": 43,
    "questionCount": 62,
    "createdAt": "2025-12-12T17:38:42.593Z",
    "updatedAt": "2025-12-12T17:38:42.593Z"
  },
  {
    "id": 39,
    "slug": "premed-biology-enzyme-kinetics-inhibition",
    "title": "Enzyme Kinetics & Inhibition (Km, Vmax, Inhibitors)",
    "description": "Pre-med/IB-level conceptual practice on enzyme kinetics: meaning of Km and Vmax, saturation, enzyme concentration vs substrate concentration, catalytic efficiency, and how different inhibitor types (competitive, noncompetitive, uncompetitive, mixed, irreversible, allosteric) change kinetics and graphs. Built to teach the concepts through tricky, realistic scenarios (no heavy calculations).",
    "tags": [
      "premed",
      "biology",
      "enzymology",
      "enzyme-kinetics",
      "inhibition",
      "km",
      "vmax",
      "michaelis-menten"
    ],
    "accessTier": "free",
    "categoryIds": [
      47
    ],
    "primaryCategoryId": 47,
    "questionCount": 60,
    "createdAt": "2025-12-12T18:20:13.398Z",
    "updatedAt": "2025-12-12T18:20:13.398Z"
  },
  {
    "id": 40,
    "slug": "premed-biology-speciation",
    "title": "Speciation & Reproductive Isolation",
    "description": "High school / IB / pre-med level questions covering allopatric, sympatric, parapatric and peripatric speciation; gene flow, drift, selection, mutation; prezygotic vs postzygotic isolation; hybrid zones, reinforcement, ring species, and common concept traps about what counts as a species.",
    "tags": [
      "premed",
      "biology",
      "speciation",
      "reproductive-isolation",
      "evolution",
      "genetics"
    ],
    "accessTier": "free",
    "categoryIds": [
      27
    ],
    "primaryCategoryId": 27,
    "questionCount": 72,
    "createdAt": "2025-12-12T19:00:53.520Z",
    "updatedAt": "2025-12-12T19:00:53.520Z"
  },
  {
    "id": 41,
    "slug": "premed-biology-prokaryotes-vs-eukaryotes",
    "title": "Prokaryotic Cells: Structure, Metabolism, and Comparison with Eukaryotes",
    "description": "Pre-med/IB-style MCQs on prokaryotic structure (cell envelope, nucleoid, plasmids, pili/flagella, ribosomes), prokaryotic metabolism (respiration, fermentation, photosynthesis, chemiosmosis), and high-yield comparisons with eukaryotic cells.",
    "tags": [
      "premed",
      "biology",
      "microbiology",
      "cell-biology",
      "prokaryotes",
      "eukaryotes",
      "comparison"
    ],
    "accessTier": "free",
    "categoryIds": [
      39
    ],
    "primaryCategoryId": 39,
    "questionCount": 50,
    "createdAt": "2025-12-13T00:36:52.662Z",
    "updatedAt": "2025-12-13T00:36:52.662Z"
  },
  {
    "id": 42,
    "slug": "premed-biology-gpcr-signaling",
    "title": "Membrane Receptors & GPCR Signaling",
    "description": "High school / pre-med / IB-style questions on membrane receptor types (GPCRs, ion channels, RTKs, intracellular receptors) with a focus on GPCR logic: why cells need membrane receptors, why cascades and amplification exist, second messengers (cAMP, IP3/DAG, Ca2+), and how signals are turned off (desensitization, GTP hydrolysis, PDE).",
    "tags": [
      "premed",
      "biology",
      "cell-biology",
      "cell-membrane",
      "signal-transduction",
      "gpcr"
    ],
    "accessTier": "free",
    "categoryIds": [
      14
    ],
    "primaryCategoryId": 14,
    "questionCount": 50,
    "createdAt": "2025-12-13T00:58:25.731Z",
    "updatedAt": "2025-12-13T00:58:25.731Z"
  },
  {
    "id": 43,
    "slug": "premed-biology-viruses",
    "title": "Viruses: Structure, Replication Cycles, and HIV",
    "description": "Pre-med/IB-style practice on virus structure, classification (DNA/RNA, enveloped/non-enveloped), replication strategies (lytic vs lysogenic), host range/tropism, and HIV as a key retrovirus example—focused on concept understanding and common traps.",
    "tags": [
      "premed",
      "biology",
      "microbiology",
      "immunology",
      "viruses",
      "virology",
      "hiv",
      "retrovirus",
      "replication"
    ],
    "accessTier": "free",
    "categoryIds": [
      39
    ],
    "primaryCategoryId": 39,
    "questionCount": 40,
    "createdAt": "2025-12-13T01:21:16.819Z",
    "updatedAt": "2025-12-13T01:21:16.819Z"
  },
  {
    "id": 44,
    "slug": "premed-biology-raas-adh",
    "title": "RAAS & ADH: Blood Pressure and Osmoregulation",
    "description": "Conceptual Pre-med/IB-style questions on the renin–angiotensin–aldosterone system (RAAS) and antidiuretic hormone (ADH): why these systems exist, what triggers them, how they amplify signals, how they change urine composition, and how they interact during dehydration, hemorrhage, salt/water loads, and common physiology-style scenarios.",
    "tags": [
      "premed",
      "biology",
      "renal",
      "renal-physiology",
      "homeostasis",
      "raas",
      "adh",
      "osmoregulation",
      "blood-pressure"
    ],
    "accessTier": "free",
    "categoryIds": [
      20
    ],
    "primaryCategoryId": 20,
    "questionCount": 50,
    "createdAt": "2025-12-13T01:46:21.550Z",
    "updatedAt": "2025-12-13T01:46:21.550Z"
  },
  {
    "id": 45,
    "slug": "premed-biology-bone-marrow-bone-growth",
    "title": "Bone Marrow, Bone Growth, and Remodeling",
    "description": "Pre-med/IB-style MCQs on red vs yellow marrow, hematopoiesis, bone growth (endochondral vs intramembranous), growth plates, and the roles/regulation of osteoblasts, osteocytes, and osteoclasts.",
    "tags": [
      "premed",
      "biology",
      "musculoskeletal",
      "tissues",
      "bone",
      "bone-marrow",
      "hematopoiesis",
      "bone-growth",
      "bone-remodeling",
      "calcium-homeostasis"
    ],
    "accessTier": "free",
    "categoryIds": [
      30
    ],
    "primaryCategoryId": 30,
    "questionCount": 40,
    "createdAt": "2025-12-13T16:05:14.629Z",
    "updatedAt": "2025-12-13T16:05:14.629Z"
  },
  {
    "id": 46,
    "slug": "premed-biology-blood-buffer-system",
    "title": "Blood Buffer System & Acid–Base Balance",
    "description": "Pre-med/IB-style questions on what buffers are, the bicarbonate buffer system, why CO2 matters, and how lungs and kidneys maintain blood pH. Includes tricky scenarios for respiratory vs metabolic acidosis/alkalosis and compensation.",
    "tags": [
      "premed",
      "biology",
      "blood",
      "hemoglobin",
      "acid-base",
      "buffers",
      "bicarbonate",
      "respiratory",
      "renal",
      "compensation"
    ],
    "accessTier": "free",
    "categoryIds": [
      31
    ],
    "primaryCategoryId": 31,
    "questionCount": 50,
    "createdAt": "2025-12-13T16:21:59.062Z",
    "updatedAt": "2025-12-13T16:21:59.062Z"
  },
  {
    "id": 47,
    "slug": "premed-biology-blood-pressure-regulation",
    "title": "Blood Pressure Regulation",
    "description": "Pre-med/IB-style questions on the determinants of arterial blood pressure (CO, TPR, compliance), rapid neural control (baroreflex, autonomic nervous system), slower hormonal control (RAAS, ADH, ANP), and classic physiology scenarios (posture, exercise, hemorrhage, temperature).",
    "tags": [
      "premed",
      "biology",
      "cardiac",
      "blood-pressure",
      "hemodynamics",
      "cardiac-output",
      "vascular-resistance",
      "baroreflex",
      "ans",
      "raas",
      "adh",
      "anp",
      "homeostasis",
      "exercise",
      "thermoregulation"
    ],
    "accessTier": "free",
    "categoryIds": [
      19
    ],
    "primaryCategoryId": 19,
    "questionCount": 50,
    "createdAt": "2025-12-13T16:45:38.682Z",
    "updatedAt": "2025-12-13T16:45:38.682Z"
  },
  {
    "id": 48,
    "slug": "premed-biology-semen-production-maturation",
    "title": "Semen Production & Sperm Maturation",
    "description": "Pre-med/IB-style questions on semen composition, accessory gland contributions (seminal vesicles, prostate, bulbourethral glands), sperm production vs maturation (seminiferous tubules vs epididymis), and key physiology concepts such as pH, coagulation/liquefaction, capacitation, and ejaculation control.",
    "tags": [
      "premed",
      "biology",
      "reproductive",
      "male-reproductive",
      "semen",
      "sperm",
      "spermatogenesis",
      "epididymis",
      "accessory-glands",
      "fertilization",
      "ejaculation",
      "hormones"
    ],
    "accessTier": "free",
    "categoryIds": [
      32
    ],
    "primaryCategoryId": 32,
    "questionCount": 50,
    "createdAt": "2025-12-13T17:27:08.476Z",
    "updatedAt": "2025-12-13T17:27:08.476Z"
  },
  {
    "id": 49,
    "slug": "premed-biology-peptide-bonds-protein-structure",
    "title": "Peptide Bonds & Levels of Protein Structure",
    "description": "Pre-med/IB-style questions on peptide bond chemistry, polypeptide directionality, and how primary/secondary/tertiary/quaternary structure are formed, stabilized, disrupted, and tested experimentally.",
    "tags": [
      "premed",
      "biology",
      "biochemistry",
      "amino-acids",
      "peptide-bond",
      "protein-structure",
      "protein-folding",
      "denaturation",
      "secondary-structure",
      "tertiary-structure",
      "quaternary-structure"
    ],
    "accessTier": "free",
    "categoryIds": [
      42
    ],
    "primaryCategoryId": 42,
    "questionCount": 50,
    "createdAt": "2025-12-13T17:42:43.064Z",
    "updatedAt": "2025-12-13T17:42:43.064Z"
  },
  {
    "id": 50,
    "slug": "premed-biology-lipids",
    "title": "Lipids: Structure, Properties, and Cell Roles",
    "description": "Pre-med/IB-style questions on lipid types (fatty acids, triglycerides, phospholipids, steroids), amphipathic behavior, membrane fluidity/permeability, lipid asymmetry and signaling, and classic conceptual traps (cis vs trans, cholesterol effects, detergents).",
    "tags": [
      "premed",
      "biology",
      "cell-membrane",
      "lipids",
      "fatty-acids",
      "phospholipids",
      "cholesterol",
      "membrane-fluidity",
      "membrane-permeability",
      "lipid-asymmetry",
      "cell-signaling",
      "detergents"
    ],
    "accessTier": "free",
    "categoryIds": [
      14
    ],
    "primaryCategoryId": 14,
    "questionCount": 40,
    "createdAt": "2025-12-13T17:52:54.395Z",
    "updatedAt": "2025-12-13T17:52:54.395Z"
  },
  {
    "id": 51,
    "slug": "premed-biology-carbohydrates",
    "title": "Carbohydrates: Sugars as Macromolecules",
    "description": "Pre-med/IB-style questions covering carbohydrate structure (mono/di/polysaccharides), glycosidic bonds, reducing sugars, alpha vs beta linkages, storage vs structural polysaccharides (starch, glycogen, cellulose, chitin), and cell biology roles (glycocalyx, glycoproteins/glycolipids, cell recognition, peptidoglycan).",
    "tags": [
      "premed",
      "biology",
      "biochemistry",
      "carbohydrates",
      "glycosidic-bond",
      "monosaccharides",
      "disaccharides",
      "polysaccharides",
      "reducing-sugars",
      "cellulose",
      "glycogen",
      "starch",
      "glycocalyx",
      "peptidoglycan"
    ],
    "accessTier": "free",
    "categoryIds": [
      42
    ],
    "primaryCategoryId": 42,
    "questionCount": 40,
    "createdAt": "2025-12-13T19:05:05.232Z",
    "updatedAt": "2025-12-13T19:05:05.232Z"
  },
  {
    "id": 52,
    "slug": "premed-biology-central-dogma-protein-synthesis",
    "title": "Central Dogma: DNA → RNA → Protein",
    "description": "Pre-med/IB-style questions on transcription and translation fundamentals: DNA strands, RNA synthesis directionality, mRNA processing, ribosome function, tRNA charging/anticodons, reading frames, and start/stop codons (including common conceptual traps).",
    "tags": [
      "premed",
      "biology",
      "molecular-biology",
      "central-dogma",
      "transcription",
      "translation",
      "genetic-code",
      "mrna",
      "trna",
      "rrna",
      "splicing"
    ],
    "accessTier": "free",
    "categoryIds": [
      16
    ],
    "primaryCategoryId": 16,
    "questionCount": 40,
    "createdAt": "2025-12-13T19:33:34.361Z",
    "updatedAt": "2025-12-13T19:33:34.361Z"
  },
  {
    "id": 53,
    "slug": "premed-chemistry-atoms-periodicity-octet",
    "title": "Atoms, Periodicity & the Octet Rule",
    "description": "Foundations of chemistry for beginners: atomic structure, isotopes and ions, periodic table groups/periods, key periodic trends, and the octet rule (including common exceptions).",
    "tags": [
      "premed",
      "chemistry",
      "atomic-structure",
      "periodic-table",
      "periodic-trends",
      "octet-rule",
      "ions",
      "bonding"
    ],
    "accessTier": "free",
    "categoryIds": [
      50
    ],
    "primaryCategoryId": 50,
    "questionCount": 40,
    "createdAt": "2025-12-13T23:12:47.745Z",
    "updatedAt": "2025-12-13T23:12:47.745Z"
  },
  {
    "id": 54,
    "slug": "premed-chemistry-group-properties-reactivity-series",
    "title": "Group Properties & Reactivity Series",
    "description": "Beginner-friendly Pre-med/IB-style questions on periodic table group properties (Group 1, 2, 17, 18), how groups react with each other (especially metals + halogens, halogen displacement), and using the metal reactivity series to predict reactions, extraction, and corrosion protection.",
    "tags": [
      "premed",
      "chemistry",
      "periodic-table",
      "groups",
      "reactivity-series",
      "displacement",
      "redox",
      "corrosion",
      "extraction"
    ],
    "accessTier": "free",
    "categoryIds": [
      50
    ],
    "primaryCategoryId": 50,
    "questionCount": 45,
    "createdAt": "2025-12-13T23:27:19.246Z",
    "updatedAt": "2025-12-13T23:27:19.246Z"
  },
  {
    "id": 55,
    "slug": "premed-chemistry-periodic-trends",
    "title": "Periodic Trends: Radius, Ionization Energy, Electronegativity & More",
    "description": "High-school/pre-med-beginner practice on periodic trends with conceptual traps: atomic/ionic radius, effective nuclear charge, shielding, first ionization energy (including common exceptions), electron affinity, electronegativity, and metallic character. Emphasis on reasoning, not memorization.",
    "tags": [
      "premed",
      "chemistry",
      "periodic-table",
      "periodic-trends",
      "atomic-radius",
      "ionic-radius",
      "ionization-energy",
      "electronegativity",
      "electron-affinity",
      "effective-nuclear-charge",
      "shielding",
      "metallic-character"
    ],
    "accessTier": "free",
    "categoryIds": [
      50
    ],
    "primaryCategoryId": 50,
    "questionCount": 40,
    "createdAt": "2025-12-13T23:44:01.812Z",
    "updatedAt": "2025-12-13T23:44:01.812Z"
  },
  {
    "id": 56,
    "slug": "premed-chemistry-stoichiometry",
    "title": "Stoichiometry: From Moles to Reactions",
    "description": "A comprehensive beginner-to-advanced progression of stoichiometry questions: mole concept, Avogadro’s constant, molar mass, balancing equations, mole ratios, limiting reagent, theoretical vs actual yield, concentrations/dilutions, precipitation reactions, simple titrations, and empirical/molecular formulas.",
    "tags": [
      "premed",
      "chemistry",
      "stoichiometry",
      "mole",
      "avogadro",
      "molar-mass",
      "balancing-equations",
      "mole-ratios",
      "limiting-reagent",
      "percent-yield",
      "concentration",
      "dilution",
      "titration",
      "empirical-formula",
      "molecular-formula",
      "precipitation",
      "gas"
    ],
    "accessTier": "free",
    "categoryIds": [
      52
    ],
    "primaryCategoryId": 52,
    "questionCount": 70,
    "createdAt": "2025-12-14T00:06:14.372Z",
    "updatedAt": "2025-12-14T00:06:14.372Z"
  },
  {
    "id": 57,
    "slug": "premed-chemistry-ideal-gas-laws",
    "title": "Ideal Gas Laws",
    "description": "Pre-med/IB-style questions building mastery of gas behavior: Boyle/Charles/Gay-Lussac/Avogadro laws, PV=nRT, unit traps, STP and molar volume, Dalton’s law and partial pressures (including gas over water), gas stoichiometry with volumes, density and molar mass from gas data, diffusion/effusion, and when real gases deviate from ideal behavior.",
    "tags": [
      "premed",
      "chemistry",
      "gases",
      "gas-laws",
      "ideal-gas-law",
      "kinetic-theory",
      "boyle-law",
      "charles-law",
      "gay-lussac",
      "avogadro-law",
      "pv=nrt",
      "stp",
      "molar-volume",
      "dalton-law",
      "partial-pressure",
      "gas-over-water",
      "gas-stoichiometry",
      "density",
      "molar-mass",
      "grahams-law",
      "real-gases"
    ],
    "accessTier": "free",
    "categoryIds": [
      53
    ],
    "primaryCategoryId": 53,
    "questionCount": 70,
    "createdAt": "2025-12-14T00:42:21.207Z",
    "updatedAt": "2025-12-14T00:42:21.207Z"
  },
  {
    "id": 58,
    "slug": "premed-chemistry-vsepr-molecular-geometry",
    "title": "Molecular Geometry & VSEPR",
    "description": "Pre-med/IB-style questions on VSEPR: electron domains vs molecular shape, lone pair effects, bond angles, trigonal bipyramidal and octahedral structures, polarity from geometry, and basic hybridization mapping.",
    "tags": [
      "premed",
      "chemistry",
      "vsepr",
      "molecular-geometry",
      "electron-domains",
      "bond-angles",
      "polarity",
      "hybridization"
    ],
    "accessTier": "free",
    "categoryIds": [
      51
    ],
    "primaryCategoryId": 51,
    "questionCount": 70,
    "createdAt": "2025-12-14T02:54:54.236Z",
    "updatedAt": "2025-12-14T02:54:54.236Z"
  },
  {
    "id": 59,
    "slug": "premed-chemistry-acids-bases",
    "title": "Acids and Bases",
    "description": "70 Pre-med/IB-style questions covering Arrhenius vs Brønsted–Lowry vs Lewis definitions, conjugate pairs, amphiprotic species, strong/weak vs concentrated/dilute, pH/pOH and Kw, buffers, titrations, salt hydrolysis, and common conceptual traps.",
    "tags": [
      "premed",
      "chemistry",
      "acids-bases",
      "pH",
      "buffers",
      "titrations",
      "conjugates",
      "strong-weak"
    ],
    "accessTier": "free",
    "categoryIds": [
      55
    ],
    "primaryCategoryId": 55,
    "questionCount": 70,
    "createdAt": "2025-12-14T03:05:50.007Z",
    "updatedAt": "2025-12-14T03:05:50.007Z"
  },
  {
    "id": 60,
    "slug": "premed-chemistry-molarity-solutions",
    "title": "Molarity & Solutions",
    "description": "70 Pre-med/IB-style questions to master solutions: solute vs solvent, molarity and unit traps, dilution and mixing, preparing standard solutions, mass percent and ppm, molality and temperature effects, electrolytes/ion concentrations, and solution stoichiometry (neutralization + precipitation).",
    "tags": [
      "premed",
      "chemistry",
      "molarity",
      "solutions",
      "dilution",
      "electrolytes",
      "stoichiometry",
      "concentration"
    ],
    "accessTier": "free",
    "categoryIds": [],
    "questionCount": 70,
    "createdAt": "2025-12-14T03:13:43.925Z",
    "updatedAt": "2025-12-14T03:13:43.925Z"
  },
  {
    "id": 61,
    "slug": "premed-chemistry-theoretical-actual-yield",
    "title": "Theoretical, Actual & Percent Yield",
    "description": "Pre-med/IB-style questions on theoretical vs actual yield, percent yield, limiting reagent links, common lab causes of yield loss (and >100% yields), multi-step overall yield, impurities, and tricky interpretation pitfalls.",
    "tags": [
      "premed",
      "chemistry",
      "yield",
      "theoretical-yield",
      "actual-yield",
      "percent-yield",
      "stoichiometry",
      "limiting-reagent"
    ],
    "accessTier": "free",
    "categoryIds": [],
    "questionCount": 70,
    "createdAt": "2025-12-14T03:26:22.375Z",
    "updatedAt": "2025-12-14T14:49:41.537Z"
  },
  {
    "id": 62,
    "slug": "premed-chemistry-rates-of-reaction",
    "title": "Rates of Reaction",
    "description": "Pre-med/IB-style questions on chemical kinetics: rate definitions and graphs, collision theory, activation energy and energy profiles, catalysts, experimental methods, rate laws and orders, Arrhenius ideas, mechanisms and rate-determining steps, and common conceptual traps.",
    "tags": [
      "premed",
      "chemistry",
      "kinetics",
      "rates",
      "collision-theory",
      "activation-energy",
      "catalysts",
      "rate-law",
      "arrhenius"
    ],
    "accessTier": "free",
    "categoryIds": [],
    "questionCount": 70,
    "createdAt": "2025-12-14T15:04:18.003Z",
    "updatedAt": "2025-12-14T15:04:18.003Z"
  },
  {
    "id": 63,
    "slug": "premed-physics-kinematics-basics",
    "title": "Kinematics Basics",
    "description": "Pre-med/IB-style conceptual questions on 1D/2D kinematics: distance vs displacement, speed vs velocity, acceleration, sign conventions, motion graphs (slope/area), constant-acceleration reasoning, free fall, projectiles, and relative motion.",
    "tags": [
      "premed",
      "physics",
      "kinematics",
      "motion",
      "velocity",
      "acceleration",
      "free-fall",
      "projectile-motion"
    ],
    "accessTier": "free",
    "categoryIds": [
      64
    ],
    "primaryCategoryId": 64,
    "questionCount": 70,
    "createdAt": "2025-12-14T15:33:09.145Z",
    "updatedAt": "2025-12-14T15:33:09.145Z"
  },
  {
    "id": 64,
    "slug": "premed-physics-mechanics-basics",
    "title": "Mechanics Basics",
    "description": "Pre-med/IB-style questions that build from Newton's laws and free-body diagrams to friction, tension, work–energy, momentum/impulse, circular motion, and torque—focused on conceptual reasoning and common traps.",
    "tags": [
      "premed",
      "physics",
      "mechanics",
      "newtons-laws",
      "forces",
      "energy",
      "momentum",
      "circular-motion",
      "torque"
    ],
    "accessTier": "free",
    "categoryIds": [
      63
    ],
    "primaryCategoryId": 63,
    "questionCount": 75,
    "createdAt": "2025-12-14T15:43:59.455Z",
    "updatedAt": "2025-12-14T15:43:59.455Z"
  },
  {
    "id": 65,
    "slug": "premed-physics-forces-dynamics",
    "title": "Forces and Dynamics",
    "description": "Pre-med/IB-style questions on forces and Newtonian dynamics: free-body diagrams, net force, action–reaction, friction, tension/connected bodies, apparent weight (elevators/orbit), drag/terminal velocity, and circular motion (including banked curves). Difficulty increases gradually and focuses on conceptual traps.",
    "tags": [
      "premed",
      "physics",
      "forces",
      "dynamics",
      "newtons-laws",
      "friction",
      "circular-motion",
      "tension",
      "free-body-diagram"
    ],
    "accessTier": "free",
    "categoryIds": [
      65
    ],
    "primaryCategoryId": 65,
    "questionCount": 75,
    "createdAt": "2025-12-14T16:25:53.277Z",
    "updatedAt": "2025-12-14T16:25:53.277Z"
  },
  {
    "id": 66,
    "slug": "premed-physics-work-energy-power",
    "title": "Work, Energy, Power",
    "description": "60 no-calculator Pre-med/IB-style questions that build from definitions and units to work signs, conservative vs non-conservative forces, energy conservation, springs, friction, force–distance graphs, efficiency, and power reasoning.",
    "tags": [
      "premed",
      "physics",
      "work",
      "energy",
      "power",
      "kinetic-energy",
      "potential-energy",
      "conservation-of-energy",
      "efficiency"
    ],
    "accessTier": "free",
    "categoryIds": [
      66
    ],
    "primaryCategoryId": 66,
    "questionCount": 60,
    "createdAt": "2025-12-14T16:39:14.864Z",
    "updatedAt": "2025-12-14T16:39:14.864Z"
  },
  {
    "id": 67,
    "slug": "premed-physics-momentum-collisions",
    "title": "Momentum and Collisions",
    "description": "Pre-med/IB-style questions on momentum (as a vector), impulse, force–time graphs, conservation conditions, center of mass motion, recoil/explosions, and 1D/2D collisions (elastic/inelastic). Designed to be conceptual and trap common misconceptions.",
    "tags": [
      "premed",
      "physics",
      "momentum",
      "collisions",
      "impulse",
      "conservation",
      "elastic",
      "inelastic",
      "recoil"
    ],
    "accessTier": "free",
    "categoryIds": [
      67
    ],
    "primaryCategoryId": 67,
    "questionCount": 75,
    "createdAt": "2025-12-14T21:41:43.232Z",
    "updatedAt": "2025-12-14T21:41:43.232Z"
  },
  {
    "id": 68,
    "slug": "premed-physics-circular-motion",
    "title": "Circular Motion",
    "description": "Pre-med/IB-style, no-calculator questions on circular motion (uniform and non-uniform): centripetal acceleration/force, angular speed/period, banked curves, vertical circles, conical pendulums, turntables, orbits, apparent weight, and common misconceptions (centrifugal vs centripetal).",
    "tags": [
      "premed",
      "physics",
      "circular-motion",
      "centripetal",
      "angular-speed",
      "orbits",
      "vertical-circles",
      "banked-curves"
    ],
    "accessTier": "free",
    "categoryIds": [
      68
    ],
    "primaryCategoryId": 68,
    "questionCount": 70,
    "createdAt": "2025-12-14T21:57:47.682Z",
    "updatedAt": "2025-12-14T21:57:47.682Z"
  },
  {
    "id": 69,
    "slug": "premed-physics-gravitation",
    "title": "Gravitation",
    "description": "Pre-med/IB-style questions covering Newton's law of gravitation, gravitational field/weight, potential energy and work, satellites/orbits (Kepler relationships), escape speed, and common conceptual traps (field vs potential, weightlessness, scaling with distance).",
    "tags": [
      "premed",
      "physics",
      "gravitation",
      "orbits",
      "escape-velocity",
      "gravitational-field",
      "kepler-laws"
    ],
    "accessTier": "free",
    "categoryIds": [
      69
    ],
    "primaryCategoryId": 69,
    "questionCount": 70,
    "createdAt": "2025-12-15T02:06:15.309Z",
    "updatedAt": "2025-12-15T02:06:15.309Z"
  },
  {
    "id": 70,
    "slug": "premed-physics-electricity-ohms-law-capacitors",
    "title": "Electricity: Ohm's Law and Capacitors",
    "description": "Pre-med style questions on current, voltage, resistance, power, series/parallel circuits, meters, internal resistance, and capacitors (Q=CV, series/parallel, energy, dielectrics, and RC charging/discharging). Focused on conceptual traps and exam-style reasoning.",
    "tags": [
      "premed",
      "physics",
      "electricity",
      "ohms-law",
      "capacitors",
      "circuits",
      "rc-circuits"
    ],
    "accessTier": "free",
    "categoryIds": [
      71
    ],
    "primaryCategoryId": 71,
    "questionCount": 75,
    "createdAt": "2025-12-15T02:23:46.249Z",
    "updatedAt": "2025-12-15T02:23:46.249Z"
  },
  {
    "id": 71,
    "slug": "premed-physics-fluids-pressure",
    "title": "Fluids and Pressure",
    "description": "Pre-med/IB-style questions on pressure, density, hydrostatics, Pascal's principle and hydraulics, buoyancy (Archimedes), atmospheric pressure devices, continuity and Bernoulli flow ideas, viscosity/laminar flow, and surface tension/capillarity. Emphasis on conceptual traps and real-world reasoning.",
    "tags": [
      "premed",
      "physics",
      "fluids",
      "pressure",
      "buoyancy",
      "bernoulli",
      "hydraulics"
    ],
    "accessTier": "free",
    "categoryIds": [
      76
    ],
    "primaryCategoryId": 76,
    "questionCount": 75,
    "createdAt": "2025-12-15T02:40:29.848Z",
    "updatedAt": "2025-12-15T02:40:29.848Z"
  },
  {
    "id": 72,
    "slug": "premed-logic-statistics-probability",
    "title": "Statistics and Probability",
    "description": "Pre-med style conceptual questions on probability fundamentals (complement, inclusion-exclusion, independence, conditional probability), counting (permutations, combinations), Bayes' theorem and base rates, descriptive statistics (mean, median, mode, standard deviation), normal distributions, hypothesis testing, correlation vs causation, and experimental design.",
    "tags": [
      "premed",
      "math",
      "statistics",
      "probability",
      "counting",
      "bayes",
      "normal-distribution",
      "hypothesis-testing",
      "correlation"
    ],
    "accessTier": "free",
    "categoryIds": [
      78
    ],
    "primaryCategoryId": 78,
    "questionCount": 75,
    "createdAt": "2025-12-15T14:49:16.312Z",
    "updatedAt": "2025-12-15T14:49:16.312Z"
  },
  {
    "id": 73,
    "slug": "premed-logic-probability-word-problems",
    "title": "Logic: Probability Word Problems",
    "description": "Pre-med style, no-calculator probability word problems (students, dice, coins, cards, balls) covering complements, conditional probability, independence, counting, expected value, Bayes/base-rate traps, and classic reasoning setups.",
    "tags": [
      "premed",
      "logic",
      "probability",
      "dice",
      "coins",
      "cards",
      "urns",
      "combinatorics",
      "bayes",
      "conditional-probability",
      "expected-value"
    ],
    "accessTier": "free",
    "categoryIds": [
      79
    ],
    "primaryCategoryId": 79,
    "questionCount": 75,
    "createdAt": "2025-12-15T15:04:04.028Z",
    "updatedAt": "2025-12-15T15:04:04.028Z"
  }
];
