"use client";

import { useState, useCallback } from "react";
import { useTranslations, useLocale } from "next-intl";
import { m, AnimatePresence } from "framer-motion";
import {
  ChevronDown,
  Archive,
  Loader2,
  Share2,
  Check,
  MessageCircle,
  GraduationCap,
} from "lucide-react";
import AnimatedSection from "@/components/shared/AnimatedSection";
import StickerBadge from "@/components/shared/StickerBadge";
import LectureCard from "./LectureCard";
import type { Course } from "@/data/universities";
import { getSubjectColor } from "@/data/universities";

interface CourseSectionProps {
  course: Course;
  universitySlug: string;
  index: number;
  defaultOpen?: boolean;
}

export default function CourseSection({
  course,
  universitySlug,
  index,
  defaultOpen = false,
}: CourseSectionProps) {
  const t = useTranslations("universities.detail");
  const locale = useLocale();
  const [open, setOpen] = useState(defaultOpen);
  const [downloading, setDownloading] = useState(false);
  const [downloadProgress, setDownloadProgress] = useState(0);
  const [copied, setCopied] = useState(false);

  const subjectColor = getSubjectColor(course.subject);

  const courseUrl =
    typeof window !== "undefined"
      ? `${window.location.origin}/${locale}/universities/${universitySlug}?course=${course.slug}`
      : "";

  const totalMaterials = course.lectures.reduce(
    (sum, l) => sum + l.materials.length,
    0,
  );

  const handleCopyLink = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(courseUrl);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = courseUrl;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }, [courseUrl]);

  const handleDownloadAll = useCallback(async () => {
    setDownloading(true);
    setDownloadProgress(0);

    try {
      const JSZip = (await import("jszip")).default;
      const { saveAs } = await import("file-saver");
      const zip = new JSZip();

      const folderName = `${course.name}-${course.professor.replace(/\s+/g, "_")}`;
      const root = zip.folder(folderName)!;

      const allAnkiCards: { front: string; back: string; lecture: string }[] =
        [];
      let processed = 0;
      const totalFiles = course.lectures.reduce((sum, l) => {
        return (
          sum +
          l.materials.filter((m) => m.downloadUrl !== "#").length
        );
      }, 0);

      for (const lecture of course.lectures) {
        for (const mat of lecture.materials) {
          if (mat.downloadUrl === "#") continue;

          const subfolder =
            mat.type === "flashcards"
              ? "flashcards"
              : mat.type === "summary"
                ? "summaries"
                : "question-banks";

          try {
            const resp = await fetch(mat.downloadUrl);
            const blob = await resp.blob();
            root
              .folder(subfolder)!
              .file(
                `${lecture.slug}-${mat.type}.pdf`,
                blob,
              );
          } catch {
            /* skip failed downloads */
          }

          if (mat.type === "flashcards" && mat.ankiCards?.length) {
            const BOM = "\uFEFF";
            const header = `# ${lecture.title} — ${mat.title} — Generated by EnterMedSchool.org\n`;
            const rows = mat.ankiCards.map(
              (c) => `${c.front}\t${c.back} | Source: entermedschool.org`,
            );
            root
              .folder("anki")!
              .file(
                `${lecture.slug}-flashcards.tsv`,
                BOM + header + rows.join("\n"),
              );

            for (const c of mat.ankiCards) {
              allAnkiCards.push({
                front: c.front,
                back: c.back,
                lecture: lecture.title,
              });
            }
          }

          processed++;
          if (totalFiles > 0) {
            setDownloadProgress(Math.round((processed / totalFiles) * 100));
          }
        }
      }

      if (allAnkiCards.length > 0) {
        const BOM = "\uFEFF";
        const header = `# ${course.name} (${course.professor}) — All Flashcards — Generated by EnterMedSchool.org\n`;
        const rows = allAnkiCards.map(
          (c) => `${c.front}\t${c.back} | Source: entermedschool.org`,
        );
        root
          .folder("anki")!
          .file("all-flashcards.tsv", BOM + header + rows.join("\n"));
      }

      root.file(
        "HOW-TO-ATTRIBUTE.txt",
        `Attribution Instructions\n========================\n\nThis resource was created by EnterMedSchool.org — Free Medical Education Resources.\n\nWhen sharing, remixing, or using this content:\n- Credit EnterMedSchool.org as the source\n- Link to https://entermedschool.org when possible\n- For flashcards: retain the "Source: entermedschool.org" line when importing to Anki\n\nThank you for supporting free medical education!\n`,
      );

      const blob = await zip.generateAsync({ type: "blob" });
      saveAs(
        blob,
        `entermedschool-${universitySlug}-${course.slug}.zip`,
      );
    } finally {
      setDownloading(false);
      setDownloadProgress(0);
    }
  }, [course, universitySlug]);

  const whatsappShareUrl = `https://wa.me/?text=${encodeURIComponent(
    `Check out free study materials for ${course.name}: ${courseUrl}`,
  )}`;

  return (
    <AnimatedSection animation="fadeUp" delay={0.1 * index}>
      <div className="overflow-hidden rounded-2xl border-3 border-ink-dark/10 bg-white shadow-chunky-sm">
        {/* Course Header */}
        <button
          type="button"
          onClick={() => setOpen(!open)}
          aria-expanded={open}
          className="flex w-full items-center gap-3 p-4 text-left transition-colors hover:bg-pastel-cream/50 sm:p-5"
        >
          <div
            className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${subjectColor.bg} ${subjectColor.text}`}
          >
            <GraduationCap className="h-5 w-5" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <h3 className="font-display text-base font-bold text-ink-dark sm:text-lg">
                {course.name}
              </h3>
              <StickerBadge color="purple" size="sm">
                {course.subject}
              </StickerBadge>
            </div>
            <p className="text-xs text-ink-muted">
              {course.professor}
              {course.professorTitle && ` — ${course.professorTitle}`}
              {course.semester && ` · ${course.semester} ${course.year ?? ""}`}
            </p>
            <p className="mt-0.5 text-xs text-ink-muted">
              {course.lectures.length} {t("lectures")} · {totalMaterials}{" "}
              {t("materials")}
            </p>
          </div>
          <ChevronDown
            className={`h-5 w-5 shrink-0 text-ink-muted transition-transform ${open ? "rotate-180" : ""}`}
          />
        </button>

        {/* Actions bar */}
        <AnimatePresence>
          {open && (
            <m.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="overflow-hidden"
            >
              <div className="border-t border-ink-dark/5 px-4 py-3 sm:px-5">
                <div className="mb-4 flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center">
                  {/* Download All ZIP */}
                  <button
                    type="button"
                    onClick={handleDownloadAll}
                    disabled={downloading}
                    className="inline-flex min-h-[44px] items-center justify-center gap-1.5 rounded-xl border-2 border-ink-dark/10 bg-white px-3 py-2 text-xs font-bold text-ink-dark transition-all hover:bg-pastel-lavender hover:shadow-chunky-sm disabled:opacity-60 sm:min-h-0 sm:py-1.5"
                  >
                    {downloading ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <Archive className="h-3.5 w-3.5" />
                    )}
                    {downloading
                      ? `${t("downloading")} ${downloadProgress}%`
                      : t("downloadAll")}
                  </button>

                  <div className="flex items-center gap-2">
                    {/* Share */}
                    <button
                      type="button"
                      onClick={handleCopyLink}
                      className={`inline-flex min-h-[44px] flex-1 items-center justify-center gap-1 rounded-xl border-2 px-3 py-2 text-xs font-bold transition-all sm:min-h-0 sm:flex-initial sm:py-1.5 ${
                        copied
                          ? "border-green-300 bg-green-50 text-green-700"
                          : "border-ink-dark/10 text-ink-muted hover:bg-pastel-lavender hover:text-showcase-purple"
                      }`}
                    >
                      {copied ? (
                        <Check className="h-3 w-3" />
                      ) : (
                        <Share2 className="h-3 w-3" />
                      )}
                      <span className="sm:inline">
                        {copied ? t("linkCopied") : t("shareCourse")}
                      </span>
                    </button>
                    <a
                      href={whatsappShareUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex min-h-[44px] flex-1 items-center justify-center gap-1 rounded-xl border-2 border-ink-dark/10 px-3 py-2 text-xs font-bold text-ink-muted transition-all hover:bg-green-50 hover:text-green-600 sm:min-h-0 sm:flex-initial sm:py-1.5"
                    >
                      <MessageCircle className="h-3 w-3" />
                      <span className="sm:inline">WhatsApp</span>
                    </a>
                  </div>
                </div>

                {/* Download progress bar */}
                {downloading && (
                  <div className="mb-4 h-1.5 overflow-hidden rounded-full bg-ink-dark/5">
                    <m.div
                      className="h-full rounded-full bg-showcase-purple"
                      initial={{ width: 0 }}
                      animate={{ width: `${downloadProgress}%` }}
                    />
                  </div>
                )}

                {/* Lecture cards */}
                <div className="space-y-3">
                  {course.lectures.map((lecture, i) => (
                    <LectureCard
                      key={lecture.id}
                      lecture={lecture}
                      index={i}
                      universitySlug={universitySlug}
                      courseSlug={course.slug}
                    />
                  ))}
                </div>
              </div>
            </m.div>
          )}
        </AnimatePresence>
      </div>
    </AnimatedSection>
  );
}
