"use client";

import { useState, useCallback } from "react";
import Image from "next/image";
import { useTranslations, useLocale } from "next-intl";
import { m, AnimatePresence } from "framer-motion";
import {
  Download,
  FileText,
  FileSpreadsheet,
  Share2,
  Check,
  MessageCircle,
  ChevronDown,
  ExternalLink,
} from "lucide-react";
import AnimatedSection from "@/components/shared/AnimatedSection";
import type { Lecture, LectureMaterial } from "@/data/universities";
import { materialTypeConfig } from "@/data/universities";

interface LectureCardProps {
  lecture: Lecture;
  index: number;
  universitySlug: string;
  courseSlug: string;
}

const MATERIAL_ICONS: Record<LectureMaterial["type"], typeof FileText> = {
  flashcards: FileText,
  summary: FileText,
  "question-bank": FileText,
};

export default function LectureCard({
  lecture,
  index,
  universitySlug,
  courseSlug,
}: LectureCardProps) {
  const t = useTranslations("universities.detail");
  const mt = useTranslations("universities.materialType");
  const locale = useLocale();
  const [showRelated, setShowRelated] = useState(false);
  const [copied, setCopied] = useState(false);

  const lectureUrl =
    typeof window !== "undefined"
      ? `${window.location.origin}/${locale}/universities/${universitySlug}#${lecture.slug}`
      : "";

  const handleCopyLink = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(lectureUrl);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = lectureUrl;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }, [lectureUrl]);

  const handleAnkiExport = useCallback(
    (material: LectureMaterial) => {
      if (!material.ankiCards?.length) return;
      const BOM = "\uFEFF";
      const header = `# ${lecture.title} — ${material.title} — Generated by EnterMedSchool.org\n`;
      const rows = material.ankiCards.map(
        (card) =>
          `${card.front}\t${card.back} | Source: entermedschool.org`,
      );
      const content = BOM + header + rows.join("\n");
      const blob = new Blob([content], {
        type: "text/tab-separated-values;charset=utf-8",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `entermedschool-${lecture.slug}-flashcards.tsv`;
      a.click();
      URL.revokeObjectURL(url);
    },
    [lecture],
  );

  const whatsappShareUrl = `https://wa.me/?text=${encodeURIComponent(
    `Check out free study materials for this lecture: ${lectureUrl}`,
  )}`;

  const handleNativeShare = useCallback(async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: lecture.title,
          text: `Free study materials for ${lecture.title}`,
          url: lectureUrl,
        });
      } catch {
        /* user cancelled */
      }
    }
  }, [lecture.title, lectureUrl]);

  return (
    <AnimatedSection animation="fadeUp" delay={0.05 * index}>
      <div
        id={lecture.slug}
        className="rounded-2xl border-3 border-ink-dark/10 bg-white shadow-chunky-sm transition-all hover:shadow-chunky scroll-mt-24"
      >
        <div className="flex flex-col sm:flex-row">
          {/* Thumbnail */}
          <div className="relative h-48 w-full shrink-0 overflow-hidden rounded-t-[13px] sm:h-auto sm:w-48 sm:rounded-l-[13px] sm:rounded-tr-none">
            <Image
              src={lecture.thumbnailUrl}
              alt={lecture.title}
              fill
              className="object-cover"
            />
            {lecture.number != null && (
              <span className="absolute left-2 top-2 flex h-7 w-7 items-center justify-center rounded-lg bg-showcase-navy/80 text-xs font-bold text-white">
                {lecture.number}
              </span>
            )}
          </div>

          {/* Content */}
          <div className="flex-1 p-4 sm:p-5">
            {/* Title row */}
            <div className="mb-2 flex items-start justify-between gap-2">
              <div>
                {lecture.number != null && (
                  <p className="text-[10px] font-bold uppercase tracking-wider text-ink-muted">
                    {t("lectureNumber", { number: lecture.number })}
                  </p>
                )}
                <h4 className="font-display text-base font-bold text-ink-dark sm:text-lg">
                  {lecture.title}
                </h4>
              </div>

              {/* Share */}
              <div className="flex shrink-0 items-center gap-1">
                <button
                  type="button"
                  onClick={
                    typeof navigator !== "undefined" && "share" in navigator
                      ? handleNativeShare
                      : handleCopyLink
                  }
                  className={`inline-flex items-center gap-1 rounded-lg border px-2 py-1 text-[11px] font-bold transition-all ${
                    copied
                      ? "border-green-300 bg-green-50 text-green-700"
                      : "border-ink-dark/10 text-ink-muted hover:bg-pastel-lavender hover:text-showcase-purple"
                  }`}
                >
                  {copied ? (
                    <Check className="h-3 w-3" />
                  ) : (
                    <Share2 className="h-3 w-3" />
                  )}
                  {copied ? t("linkCopied") : t("share")}
                </button>
                <a
                  href={whatsappShareUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center rounded-lg border border-ink-dark/10 p-1 text-ink-muted transition-all hover:bg-green-50 hover:text-green-600"
                >
                  <MessageCircle className="h-3.5 w-3.5" />
                </a>
              </div>
            </div>

            {lecture.description && (
              <p className="mb-3 text-sm text-ink-muted">
                {lecture.description}
              </p>
            )}

            {/* Materials */}
            <div className="flex flex-wrap gap-2">
              {lecture.materials.map((mat) => {
                const config = materialTypeConfig[mat.type];
                return (
                  <div key={mat.id} className="flex items-center gap-1">
                    <a
                      href={mat.downloadUrl}
                      download
                      className={`inline-flex items-center gap-1.5 rounded-lg border-2 px-2.5 py-1 text-xs font-bold transition-all hover:shadow-chunky-sm ${config.bgColor} border-transparent hover:border-ink-dark/10`}
                    >
                      <Download className="h-3 w-3" />
                      <span className={config.color}>{mt(mat.type)}</span>
                      {mat.fileSize && (
                        <span className="text-[10px] text-ink-muted">
                          {mat.fileSize}
                        </span>
                      )}
                    </a>
                    {mat.type === "flashcards" && mat.ankiCards?.length ? (
                      <button
                        type="button"
                        onClick={() => handleAnkiExport(mat)}
                        className="inline-flex items-center gap-1 rounded-lg border-2 border-transparent bg-showcase-blue/10 px-2.5 py-1 text-xs font-bold text-showcase-blue transition-all hover:border-ink-dark/10 hover:shadow-chunky-sm"
                      >
                        <FileSpreadsheet className="h-3 w-3" />
                        {t("ankiImport")}
                      </button>
                    ) : null}
                  </div>
                );
              })}
            </div>

            {/* Related Content */}
            {lecture.relatedContent.length > 0 && (
              <div className="mt-3">
                <button
                  type="button"
                  onClick={() => setShowRelated(!showRelated)}
                  aria-expanded={showRelated}
                  className="flex items-center gap-1 text-xs font-semibold text-showcase-purple hover:underline"
                >
                  <ChevronDown
                    className={`h-3 w-3 transition-transform ${showRelated ? "rotate-180" : ""}`}
                  />
                  {t("relatedContent")} ({lecture.relatedContent.length})
                </button>
                <AnimatePresence>
                  {showRelated && (
                    <m.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.2 }}
                      className="overflow-hidden"
                    >
                      <div className="mt-2 flex flex-wrap gap-1.5">
                        {lecture.relatedContent.map((rc) => (
                          <a
                            key={rc.id}
                            href={rc.url}
                            className="inline-flex items-center gap-1 rounded-lg bg-pastel-lavender/60 px-2 py-1 text-[11px] font-semibold text-showcase-purple transition-all hover:bg-pastel-lavender"
                          >
                            <ExternalLink className="h-2.5 w-2.5" />
                            {rc.title}
                          </a>
                        ))}
                      </div>
                    </m.div>
                  )}
                </AnimatePresence>
              </div>
            )}
          </div>
        </div>
      </div>
    </AnimatedSection>
  );
}
